*Manual decoding and curation for CSSCD;
libname phase23 "/home/sasuser/CSSCD/Phase2_3/pub_sd2s";
libname ophase23 '/home/sasuser/CSSCD/phase23meta';

proc copy inlib=phase23 outlib=ophase23 noclone datecopy;
run;

*Abgn.fmt;

PROC FORMAT;
	*Format NO_YES used for the following variables: ABGPOX ABGCOOX;
	VALUE NO_YES 1='NO' 2='YES';
	VALUE ABGIRPT 1='NOT RECEIVED' 2='RECEIVED';

proc datasets library=ophase23;
	modify abg_pubn;
	FORMAT ABGPOX ABGCOOX ABGTRNSC NO_YES. ABGIRPT ABGIRPT.;
	RUN;

proc export data=ophase23.abg_pubn 
		outfile="/home/sasuser/CSSCD/output/phase23_abg_pubn.csv";
	delimiter=',';
run;

*Acbcn.fmt;

PROC FORMAT;
	*Format TIMESPNT used for the following variables: TIMSPORA TIMSPORB TIMSPORC TIMEACTA TIMEACTB TIMEACTC;
	VALUE TIMESPNT 1='LESS THAN AVERAGE' 2='AVERAGE' 3='MORE THAN AVERAGE';
	*Format SKILL used for the following variables: SKILLSPA SKILLSPB SKILLSPC SKILACTA SKILACTB SKILACTC;
	VALUE SKILL 1='BELOW AVERAGE' 2='AVERAGE' 3='ABOVE AVERAGE';
	*Format ACTIVE used for the following variables: HOWACTA HOWACTB HOWACTC;
	VALUE ACTIVE 1='LESS ACTIVE' 2='AVERAGE' 3='MORE ACTIVE';
	*Format HOW_WELL used for the following variables: HOWELLJA HOWELLJB HOWELLJC;
	VALUE HOW_WELL 1='BELOW AVERAGE' 2='AVERAGE' 3='ABOVE AVERAGE';
	VALUE NUMFRIEN 1='NONE' 2='ONE' 3='TWO OR THREE' 4='FOUR OR MORE';
	VALUE TIMWEEKF 1='LESS THAN ONE' 2='ONE OR TWO' 3='THREE OR MORE';
	*Format GETALONG used for the following variables: GETALSIB GETALPEE GETALPAR PLAYWORK;
	VALUE GETALONG 1='WORSE' 2='ABOUT AVERAGE' 3='BETTER' 
		9='HAS NO BROTHERS/SISTERS';
	*Format SCHOOL used for the following variables: SUBJECTA SUBJECTB SUBJECTC SUBJECTD SUBJECTE SUBJECTF SUBJECTG;
	VALUE SCHOOL 1='FAILING' 2='BELOW AVERAGE' 3='AVERAGE' 4='ABOVE AVERAGE';
	*Format NO_YES used for the following variables: SPECCLAS REPGRADE OACAPRO;
	VALUE NO_YES 1='YES' 2='NO';
	*Format ITEMS used for the following variables: ACTYOUNG ALLERGY ARGUES ASTHMA
                            BEHVOSEX BMOUTTOI BRAGGING CANTCONC OBSESSIO
                            RESTLESS TOODEP LONELIN CONFUSED CRIES CRUELAN
                            CRUELOTH DAYDREAM DEMATTEN DESTROWN DESTROTH
                            DISOBHOM DISOBSCH DSNTEATW DSNTGALO DSNTGUIL JEALOUS
                            EATNONFO FEARS FEARSCHL FEARDOBD PERFECT FEARNOLV
                            OTHOTGH INFERIOR ACCPRONE GETSFIGH TEASED TROUBCHI
                            HEARSOUN IMPULSIV LIKEBEAL LYCHEAT BITEFING NERVOUS
                            TWITCH NIGHTMAR DISLIKED CONSTIP ANXIOUS FEELDIZZ
                            FEELGUIL OVEREATS OVERTIRE OVERWT PAINS HEADACHE
                            NAUSEA EYEPROB RASHES STOMACHE VOMITING OTHER
                            ATTAKPEO PICKBODY PLSEXPUB PLAYSEXP POORSCHL CLUMSY
                            PLOLDKID PLYOUKID NOTALK REPEATAC RUNSAWAY SCREAMS
                            SECRETIV SEETHING SELFCONS SETFIRES SEXPROB CLOWNING
                            SHY SLEELESS SLEEPMOR PLAYSWBM SPEEPROB STARBLAN
                            STEALHOM STEALOHO STORTHNG STRANBEH STRANIDE STUBBORN
                            SUDMOOCH SULKS SUSPICI SWEARING TKWKSLEE
                            TKTOOMUC TEASES TANTRUMS THINKSEX THREATEN THUMBSUC
                            NEATNESS TROUSLEE TRUANCY SLOWMOV SAD LOUD ALCOHOL
                            VANDAL WETSSELF WETSBED WHINING WITHDRAW WORRYING LASTOTH;
	VALUE ITEMS 0='NOT TRUE' 1='SOMEWHAT/SOMETIMES TRUE' 2='VERY/OFTEN TRUE';

proc datasets library=ophase23;
	modify acbcpubn;
	format TIMSPORA TIMSPORB TIMSPORC TIMEACTA TIMEACTB TIMEACTC TIMESPNT.
	SKILLSPA SKILLSPB SKILLSPC SKILACTA SKILACTB SKILACTC SKILL.
	HOWACTA HOWACTB HOWACTC ACTIVE.
	HOWELLJA HOWELLJB HOWELLJC HOW_WELL.
	NUMFRIEN NUMFRIEN.
	TIMWEEKF TIMWEEKF.
	GETALSIB GETALPEE GETALPAR PLAYWORK GETALONG.
	SUBJECTA SUBJECTB SUBJECTC SUBJECTD SUBJECTE SUBJECTF SUBJECTG SCHOOL.
	SPECCLAS REPGRADE OACAPRO NO_YES ACTYOUNG ALLERGY ARGUES ASTHMA BEHVOSEX 
		BMOUTTOI BRAGGING CANTCONC OBSESSIO RESTLESS TOODEP LONELIN CONFUSED CRIES 
		CRUELAN CRUELOTH DAYDREAM DEMATTEN DESTROWN DESTROTH DISOBHOM DISOBSCH 
		DSNTEATW DSNTGALO DSNTGUIL JEALOUS EATNONFO FEARS FEARSCHL FEARDOBD PERFECT 
		FEARNOLV OTHOTGH INFERIOR ACCPRONE GETSFIGH TEASED TROUBCHI HEARSOUN IMPULSIV 
		LIKEBEAL LYCHEAT BITEFING NERVOUS TWITCH NIGHTMAR DISLIKED CONSTIP ANXIOUS 
		FEELDIZZ FEELGUIL OVEREATS OVERTIRE OVERWT PAINS HEADACHE NAUSEA EYEPROB 
		RASHES STOMACHE VOMITING OTHER ATTAKPEO PICKBODY PLSEXPUB PLAYSEXP POORSCHL 
		CLUMSY PLOLDKID PLYOUKID NOTALK REPEATAC RUNSAWAY SCREAMS SECRETIV SEETHING 
		SELFCONS SETFIRES SEXPROB CLOWNING SHY SLEELESS SLEEPMOR PLAYSWBM SPEEPROB 
		STARBLAN STEALHOM STEALOHO STORTHNG STRANBEH STRANIDE STUBBORN SUDMOOCH SULKS 
		SUSPICI SWEARING TKWKSLEE TKTOOMUC TEASES TANTRUMS THINKSEX THREATEN THUMBSUC 
		NEATNESS TROUSLEE TRUANCY SLOWMOV SAD LOUD ALCOHOL VANDAL WETSSELF WETSBED 
		WHINING WITHDRAW WORRYING LASTOTH ITEMS.;
	run;

proc export data=ophase23.acbcpubn 
		outfile="/home/sasuser/CSSCD/output/phase23_acbcpubn.csv";
	delimiter=',';
run;

*Accn.fmt;

PROC FORMAT;
	*Format NO_YES used for the following variables: ACCASSMT ACCTRNSC;
	VALUE NO_YES 1='NO' 2='YES';
	VALUE ACCRSN 1='1=POOR MOTIVATION' 2='2=ATTENTIONAL DIFFICULTIES' 
		4='4=BEHAVIORAL PROBLEMS' 8='8=LANGUAGE BARRIERS' 16='16=MOTOR IMPAIRMENT' 
		32='32=HEARING DIFFICULTIES' 64='64=VISUAL DIFFICULTIES' 
		128='128=MEDICATION EFFECTS' 256='256=OTHER';

proc datasets library=ophase23;
	modify acc_pubn;
	FORMAT ACCASSMT ACCTRNSC NO_YES. ACCRSN ACCRSN.;
	RUN;

proc export data=ophase23.acc_pubn 
		outfile="/home/sasuser/CSSCD/output/phase23_acc_pubn.csv";
	delimiter=',';
run;

*cvaadj.fmt;

PROC FORMAT;
	* Format STRK is defined for the following variables: DY_STRK DD_STRK NS_STRK
        STRK;
	VALUE STRK 1='NO STROKE' 2='STROKE'
              -7='NOT APPLICABLE'
              -9='MISSING';
	* Format STRKT is defined for the following variables DY_STRKT DD_STRKT NS_STRKT
        STRKT;
	VALUE STRKT 1='INFARCTIVE' 2='INTRAPAR HEMORRHAGE' 3='SUBARCH HEMORRHAGE' 
		4='INTRAVENT HEMORRHAGE' -7='NOT APPLICABLE' -9='MISSING';

proc datasets library=ophase23;
	modify cvaadpub;
	format DY_STRK DD_STRK NS_STRK STRK STRK.
        DY_STRKT DD_STRKT NS_STRKT STRKT STRKT.;
	run;

proc export data=ophase23.cvaadpub 
		outfile="/home/sasuser/CSSCD/output/phase23_cvaadpub.csv";
	delimiter=',';
run;

*Dthn.fmt;

PROC FORMAT;
	VALUE DTHCOHRT 1='PEDIATRIC' 2='NEWBORN' 3='OTHER';
	VALUE DTHRLP 1='PRONOUNCED DOA' 2='DIED W/IN 24 HRS' 3='DIED>24 HRS AFT ADM';
	VALUE DTHICSE 1='INFECTION' 2='OTHER';
	*Format NO_YES used for the following variables: DTHSUMR DTHCERT DTHCERTR
                            DTHINFF DTHINFFR DTHINFMP DTHINFMR DTHINFOT
                            DTHATPR
                            DTHCLIV DTHCKID DTHAHRT DTHALNG DTHALIV DTHAKID















																														                            DTHEV DTHCOMM DTHTRNSC;
	VALUE NO_YES 1='NO' 2='YES';
	VALUE DTHATPSY 1='NO' 2='YES' 9='DONT KNOW';

proc datasets library=ophase23;
	modify dth_pubn;
	FORMAT DTHCOHRT DTHCOHRT. DTHRLP DTHRLP.
                DTHSUMR DTHCERTR DTHINFF DTHINFFR DTHINFMP 
		DTHINFMR DTHINFOT DTHATPR DTHALIV DTHAKID DTHEV DTHCOMM DTHTRNSC NO_YES.
                DTHATPSY DTHATPSY.
                DTHICSE DTHICSE.;
	RUN;

proc export data=ophase23.dth_pubn 
		outfile="/home/sasuser/CSSCD/output/phase23_dth_pubn.csv";
	delimiter=',';
run;

*cvan.fmt;

PROC FORMAT;
	VALUE CVWHERE 1='CSSCD CENTER' 2='OTHER';
	VALUE CVTYPE 1='TIA' 2='INFARCTIVE STROKE' 3='CEREBRAL HEMORRHAGE';
	*Format NO_YES used for the following variables: ADJUDIC CVHOSP CVTRANS CVCONS
                            CVCMENT CVSPDIF CVPARAL CVSWDIF CVVISDIF CVDIZZ CVSEIZ
                            CVHACHE CVACFEV CVPAINEV CVACCHSY CVACANEM CVGENANT



						                            CVPRIAP CVNEUEVL CVEVENT CVTRANSN CVTRNSC CVDIE;
	VALUE NO_YES 1='NO' 2='YES';
	*Format IMAGING used for the following variables: CVMRI CVCTSCN CVPETSCN CVMRA










																				                                                  CVART CVTCD;
	VALUE IMAGING 1='NORMAL' 2='ABNORMAL' 3='NOT DONE';

proc datasets library=ophase23;
	modify cva_pubn;
	FORMAT CVWHERE CVWHERE. CVTYPE CVTYPE. ADJUDIC CVHOSP CVTRANS CVCONS CVCMENT 
		CVSPDIF CVPARAL CVSWDIF CVVISDIF CVDIZZ CVSEIZ CVHACHE CVACFEV CVPAINEV 
		CVACCHSY CVACANEM CVGENANT CVPRIAP CVNEUEVL CVEVENT CVTRANSN CVDIE CVTRNSC 
		NO_YES.
                CVMRI CVCTSCN CVPETSCN CVMRA CVART CVTCD 
		IMAGING.;
	RUN;

proc export data=ophase23.cva_pubn 
		outfile="/home/sasuser/CSSCD/output/phase23_cva_pubn.csv";
	delimiter=',';
run;

*fesn.fmt;

PROC FORMAT;
	VALUE FESRSEX 1='M' 2='F';
	VALUE FESREL 1='MOTHER' 2='FATHER' 3='SON/DAUGHTER' 4='OTHER';
	* Format FESITEMS is defined for variables: FESRAW1-FESRAW90;
	VALUE FESITEMS 1='True' 2='False';

proc datasets library=ophase23;
	modify fes_pubn;
	format FESRSEX FESRSEX.
	  FESREL FESREL.
	  FESRAW1-FESRAW90 FESITEMS.;
	run;

proc export data=ophase23.fes_pubn 
		outfile="/home/sasuser/CSSCD/output/phase23_fes_pubn.csv";
	delimiter=',';
run;

*hxpn.fmt;

PROC FORMAT;
	VALUE HXPIN 1='PATIENT' 2='PARENT' 3='LEGAL GUARDIAN' 4='OTHER';
	*Format NO_YES used for the following variables: HXMEDS HXMPEN HXMPENLV
        HXMERYTH HXMERYLV HXMFOL HXMFOLLV HXMASM HXMASMLV HXMPPN HXMPPNLV
        HXMIRC HXMIRCLV HXCONPLV HXMOTH HXMOTHLV HXRPHYDR HXRPBUTY
        HXOTHPRO HXRX HXCVA HXSEIZR HXSPLS HXAPC HXSEP HXPNEU HXMENI
        HXOSTEO HXPRI HXTRANS HXSURG HXPC HXOTHRX HXMPER 
        HXSCH HXREPGR HXCMPLU
        HXCMPANH HXCMPANS HXCMPSCR HXCTRN HXCTRNLV HXCTRNCV  HXCTRNPN
        HXCTRNO HXASTH HXCHRTF HXCLIVF HXCRENF HXIRNOV HXDIAB
        HXRHFEV HXTB HXSEIZ HXHIVP HXLDIS HXADD HXDYSL HXEBLL
        HXCDIS HXBSTAT HXTRSL HXTRNSC HXPCARE HXMIRN HXMIRNLV HXMPROPS
        HXMPRLV HXRCHPRO HXPROPS HXLIVS HXSCHDIL HXTEASC HXREF HXRX1
        HXRX2 HXRX3 HXPCARE;
	VALUE NO_YES 1='NO' 2='YES';
	VALUE HXCONP 1='NO' 2='YES' 3='N/A' 8='N/A';
	VALUE HXWALK 1='NO' 2='YES' 8='N/A-TOO YOUNG';
	VALUE HXSCHDM 1='NO' 2='YES' 8='N/A-SCHOOL NOT IN SESSION';
	*Format PT_SEEN used for the following variables: HXTRANSS HXPCS ;
	VALUE PT_SEEN 1='CSSCD SITE' 2='NON-CSSCD SITE';
	*Format CVA_ASMA used for the following variables: HXEVHS HXEVHA HXNOWALK;
	VALUE CVA_ASMA 1='NO' 2='YES' 3='N/A';
	VALUE HXENUR 1='NO' 2='YES';
	VALUE HXENURN 1='<1 NIGHT PER MONTH' 2='1-7 NIGHTS PER MONTH' 
		3='8-14 NIGHTS PER MONTH' 4='15-21 NIGHTS PER MONTH' 5='>21 NIGHT PER MONTH';
	VALUE HXGETUP 1='NO' 2='YES';
	VALUE HXGETUPN 1='<1 NIGHT PER MONTH' 2='1-7 NIGHTS PER MONTH' 
		3='8-14 NIGHTS PER MONTH' 4='15-21 NIGHTS PER MONTH' 5='>21 NIGHT PER MONTH';
	*Format BREATHE used for the following variables: HXDIFBR HXSNORE HXSTBR;
	VALUE BREATHE 1='NEVER' 2='OCCASIONALLY' 3='FREQUENTLY' 4='ALWAYS';
	VALUE HXANINC 1='LESS THAN $5,000' 2='$5,000 - $9,999' 3='$10,000 - $14,999' 
		4='$15,000 - $19,999' 5='$20,000 - $29,999' 6='$30,000 - $49,999' 
		7='$50,000 - $69,999' 8='$70,000 - $99,999' 77='REFUSED TO ANSWER' 
		99='DO NOT KNOW';
	*Format HXPFS used for the following variables: HXPFST1 HXPFST2;
	VALUE HXPFS 1='NO SYMPTOMS' 2='MINOR SYMPTOMS' 3='MILD SYMPTOMS' 
		4='MODERATE SYMPTOMS' 5='SEVERE SYMPTOMS';
	VALUE HXCORRL 1='NO' 2='YES' 3='N/A PT BLIND';
	VALUE HXFLUYR 1='NO' 2='YES' 3='DOES NOT KNOW';
	*Format VACCINE used for the following variables: HXFLU HXVPNE
        HXVHEPB HXVMENIN;
	VALUE VACCINE 1='NO' 2='YES' 9='DOES NOT KNOW';
	VALUE HXREC 1='NO' 2='YES' 8='N/A NO ACTIVITIES';
	VALUE HXHLTHY 1='ALL OF THE TIME' 2='MOST OF THE TIME' 3='SOME OF THE TIME' 
		4='ALMOST NEVER' 5='NEVER';
	*Format HLTHRATE used for the following variables: HXHLTH1 HXHLTH2
        HXHLTH3;
	VALUE HLTHRATE 1='MUCH BETTER' 2='SOMEWHAT BETTER' 3='SAME' 4='SOMEWHAT WORSE' 
		5='MUCH WORSE';
	VALUE HXPRINC 1='SOCIAL SECURITY' 2='SSI OR WELFARE' 
		8='JOB OF PARENT/GUARDIAN' 9='OTH HOUSEHOLD CONTRIB' 11='OTHER SOURCE' 
		77='REFUSED TO ANSWER' 99='DO NOT KNOW';
	*Format OUTCOME used for the following variables:HXOUT1 HXOUT2 HXOUT3;
	VALUE OUTCOME 1='NORMAL' 2='ABNORMAL';

proc datasets library=ophase23;
	modify hxp_pubn;
	FORMAT HXPIN HXPIN. 
                HXMEDS HXMPEN HXMPENLV HXMERYTH HXMERYLV HXMFOL 
		HXMFOLLV HXMASM HXMASMLV HXMPPN HXMPPNLV HXMIRC HXMIRCLV HXCONPLV HXMOTH 
		HXMOTHLV HXRPBUTY HXOTHPRO HXRX HXCVA HXSEIZR HXSPLS HXAPC HXSEP HXPNEU 
		HXMENI HXOSTEO HXPRI HXTRANS HXSURG HXPC HXOTHRX HXMPER HXSCH HXREPGR HXCMPLU 
		HXCMPANH HXCMPANS HXCMPSCR HXCTRN HXCTRNLV HXCTRNCV HXCTRNPN HXCTRNO HXASTH 
		HXCHRTF HXCLIVF HXCRENF HXIRNOV HXDIAB HXRHFEV HXTB HXSEIZ HXHIVP HXLDIS 
		HXADD HXDYSL HXEBLL HXCDIS HXBSTAT HXTRSL HXTRNSC HXPCARE HXMIRN HXMIRNLV 
		HXMPROPS HXMPRLV HXRCHPRO HXPROPS HXLIVS HXSCHDIL HXTEASC HXREF HXRX1 HXRX2 
		HXRX3 HXPCARE NO_YES.
                HXCONP HXCONP. HXWALK HXWALK. 
                HXSCHDM HXSCHDM. HXTRANSS HXPCS PT_SEEN.
                HXEVHS HXEVHA HXNOWALK CVA_ASMA. 
                HXENUR HXENUR. HXENURN HXENURN.
                HXGETUP HXGETUP. HXGETUPN HXGETUPN. HXDIFBR 
		HXSNORE HXSTBR BREATHE. 
                HXPFST1 HXPFST2 HXPFS. HXANINC HXANINC. HXCORRL 
		HXCORRL.
                HXFLUYR HXFLUYR. HXFLU HXVPNE HXVHEPB HXVMENIN 
		VACCINE.
                HXREC HXREC. HXHLTHY HXHLTHY. 
                HXHLTH1-HXHLTH3 HLTHRATE. 
                HXPRINC HXPRINC. HXOUT1-HXOUT3 OUTCOME.;
	RUN;

proc export data=ophase23.hxp_pubn 
		outfile="/home/sasuser/CSSCD/output/phase23_hxp_pubn.csv";
	delimiter=',';
run;

*Intn.fmt;

PROC FORMAT;
	VALUE ID2F 1='1-PH2 ENTRY' 2='2-PH2 SEMI 1 FU' 3='3-PH2 ANN 1 FU' 
		4='4-PH2 SEMI 2 FU' 5='5-PH2 ANN 2 FU' 6='6-PH2 SEMI 3 FU' 7='7-PH2 ANN 3 FU' 
		8='8-PH2 SEMI 4 FU' 9='9-PH2 ANN 4 FU' 11='11-PH 3-ENTRY' 
		12='12-PH 3 SEMI 1 FU' 13='13-PH 3 ANN 1 FU' 14='14-PH 3 SEMI 2 FU' 
		15='15-PH 3 ANN 2 FU' 16='16-PH 3 SEMI 3 FU' 17='17-PH 3 ANN 3 FU' 
		18='18-PH 3 SEMI 4 FU' 19='19-PH 3 ANN 4 FU';
	*Format NO_YES used for the following variables: INTALIVE INTMOVE















																														        INTFUCL INTREFSL INTTRNSF INTREFER;
	VALUE NO_YES 1='NO' 2='YES' 9='DONT KNOW';
	VALUE INTPHONE 1='NO' 2='YES' 3='N/A NO PHONE';
	VALUE INTPE 1='NO' 2='YES' 3='N/A SEMI ANNUAL';
	VALUE INTTRRSN 1='CHOICE' 2='NO INS COVERAGE' 3='OTHER';
	* Format NO_YES2F used for the following variables: INTADDR INTHEAR


				        INTSPEEC INTOPTHM INTDELAY INTNEURO INTIMAGE INTOSA INTOTHER INTTRNSC;
	VALUE NO_YES2F 1='NO' 2='YES';
	VALUE INTPERSN 1='MOVED OUTSIDE AREA' 2='REFUSAL-FU ELSEWHERE' 
		3='REFUSAL-OTHER REASON' 6='MISSED APPT/OTH REAS' 8='LOST-NO ADDRESS/PHONE' 
		10='OTHER REASON';
	*Format SPECTEST used for the following variables: INTMRI INTNP INTPSY
        INTPFT INTABG;
	*The SPECTEST variables will not have edits reissued;
	VALUE SPECTEST 1='NOT REQUIRED' 2='UNABLE TO COOPERATE' 3='DONE' 4='SCHEDULED' 
		5='REFUSED' 6='MISSED APPOINTMENTS' 7='NOT DONE OTHER REAS';
	VALUE INTCONSF 1='NO' 2='YES';
	VALUE INTDTHF 1='NO' 2='YES';

proc datasets library=ophase23;
	modify int_pubn;
	FORMAT INTID2 ID2F. INTALIVE INTMOVE INTFUCL INTREFSL INTTRNSF INTREFER 
		NO_YES. INTPHONE INTPHONE. INTTRRSN INTTRRSN.
 		INTADDR INTHEAR INTSPEEC INTOPTHM INTDELAY INTNEURO INTIMAGE INTOSA 
		INTOTHER INTTRNSC NO_YES2F. INTPE INTPE. INTPERSN INTPERSN.
 		INTCONSF INTCONSF. INTMRI INTNP INTPSY INTPFT INTABG SPECTEST.;
	RUN;

proc export data=ophase23.int_pubn 
		outfile="/home/sasuser/CSSCD/output/phase23_int_pubn.csv";
	delimiter=',';
run;

*lab.fmt;

PROC FORMAT;
	VALUE ID2F 1='1-PH2 ENTRY VIS' 3='3-PH2 ANN 1 VIS' 5='5-PH2 ANN 2 VIS' 
		7='7-PH2 ANN 3 VIS' 9='9-PH2 ANN 4 VIS' 11='11-PH3 ENTRY VIS' 
		13='13-PH3 ANN 1 VIS' 15='15-PH3 ANN 2 VIS' 17='17-PH3 ANN 3 VIS' 
		19='19-PH3 ANN 4 VIS';
	VALUE LABTRANS 1='NO' 2='YES';
	VALUE LABFMTH 1='ALKALINE DENATURATION' 2='OTHER METHOD';
	* Format DIPSTICK is defined for variables LABURPRO LABURHB;
	VALUE DIPSTICK 1='NEGATIVE' 2='TRACE' 3='1+' 4='2+' 5='3+' 6='4+';
	VALUE LABIRPT 1='NO' 2='YES';
	VALUE LABA2MTH 1='COLUMN CHROMATOGRAPHY' 2='OTHER';
	VALUE LABDIAG 1='SS' 2='SC' 3='SB+THAL' 4='SB0THAL' 5='SS ALPHA THAL' 
		6='OTHER';
	VALUE LABOMTH 1='NO' 2='YES';

proc datasets library=ophase23;
	modify lab_pubn;
	format LABID2 ID2F.
	 LABTRANS LABTRANS.
	 LABFMTH LABFMTH.
	 LABURPRO LABURHB DIPSTICK.
	 LABIRPT LABIRPT.
	 LABA2MTH LABA2MTH.
	 LABDIAG LABDIAG.
	 LABOMTH LABOMTH.;
	run;

proc export data=ophase23.lab_pubn 
		outfile="/home/sasuser/CSSCD/output/phase23_lab_pubn.csv";
	delimiter=',';
run;

*lisrn.fmt;

PROC FORMAT;
	*Format NO_YES used for the following variables: LISNEWH LISNEWMN LISMOUT
                            LISPRSEP LISPRDIV LISMADI LISPADI LISBSDI
                            LISMAREM LISPAREM LISSTOLE LISBURGL LISATTAK
                            LISHOSP LISACCID LISHLTIM LISMALFE
                            LISMBTR LISMWRS LISMACC LISMHOSP LISMILL
                            LISMLSTJ LISMWORK LISPALFE LISPBTR LISPWRS
                            LISPACC LISPHOSP LISPILL LISPLSTJ LISPWORK
                            LISBRSIS LISSTEP LISBSBTR LISBSWRS LISBSACC
                            LISBSHSP LISBSILL LISBSBTH LISRBTR LISRWSE
                            LISRACC LISRILL LISREMOT LISRECIL LISRDIED
                            LISRMVD LISMOTH LISMMEDC LISFATH LISFMEDC
                            LISBRSS LISSBRSS LISBSMED LIS1ADLT LISTEAM
                            LISTRYOT LISTRBLS LISSUSCH LISHELD LISAWARD
                            LISTINFL LISSCGRP LISDROP LISNEWS LISFBTR
                            LISFWRS LISNEWFR LISNEWBF LISFDROP LISOTM
                            LISOTRY LISFDIED LISFMVD LISSDATE LISFLOVE
                            LISREJCT LISSTDY LISBRKUP LISRELCB LISRECW













																										                            LISCBGFR LISCOMM;
	VALUE NO_YES 1='NO' 2='YES';
	VALUE LISHOMES 1='IS IT A BETTER HOME' 2='IS IT NO BETTER OR WORSE' 
		3='IS IT A WORSE HOME';
	VALUE LISPLIVW 1='MOTHER' 7='OTHER';
	*Format EVENTS used for the following variables: LISNEWMS LISMOUTS LISMARMS
                            LISPARMS;
	VALUE EVENTS 1='MADE THINGS BETTER' 2='MADE NO DIFFERENCE' 
		3='MADE THINGS WORSE';
	*Format ABOUT_PT used for the following variables:LISKEPTU LISSPACE LISHEAT
                          LISCOOL LISQUIET LISSAFE LISMEDC LISFDCL LISLIVE













																										                          LISOTHTH LISACTET LISEXTRA;
	VALUE ABOUT_PT 1='DEFINITELY NO' 2='MAINLY NO' 3='MAINLY YES' 
		4='DEFINITELY YES';
	*Format WORK used for the following variables: LISWORK LISMAWKN LISPAWKN;
	VALUE WORK 1='NO' 2='YES PART-TIME' 3='YES FULL-TIME';
	*Format SCHOOL used for the following variables: LISMASCH LISPASCH;
	VALUE SCHOOL 3='COMPLETED GRADE 9 OR LESS' 4='COMPLETED SOME HIGH SCHOOL' 
		5='COMPLETED HIGH SCHOOL/GRADUATED/GED' 6='COMPLETED SOME TECHNICAL TRAINING' 
		7='COMPLETED SOME COLLEGE/ASSOCIATES DEGREE' 
		8='RECEIVED AT LEAST BACHELORS DEGREE';
	*Format RELATE used for the following variables: LISMHELP LISMARGU
                            LISMCRIT LISMFEEL LISMNERV LISMCHR LISMANGR
                            LISMRSPT LISMEXP LISMFUN LISMSTRT LISMPRES
                            LISPHELP LISPARGU LISPCRIT LISPFEEL LISPNERV
                            LISPCHR LISPANGR LISPRSPT LISPEXP LISPFUN
                            LISPSTRT LISPPRES LISBSHLP LISBSARG LISBSCRT
                            LISBSFEL LISBSNRV LISBSCHR LISBSANG LISBSRSP
                            LISBSEXP LISBSFUN LISBSSUP LISRHELP LISRARGU
                            LISRCRIT LISRFEEL LISRNERV LISRCHR LISRANGR
                            LISRRSPT LISREXP LISRFUN LISARGU LISCRIT
                            LISNERVS LISANGRY LISEXPCT LISSARGU LISSCRIT
                            LISSNERV LISSANG LISSEXP LISSPRES LISTHELP
                            LISTARGU LISTCRIT LISTFEEL LISTNERV LISTCHR
                            LISTANGR LISTRSPT LISTEXP LISTFUN LISFHELP
                            LISFARGU LISFCRIT LISFFEEL LISFNERV LISFCHR
                            LISFANGR LISFRSPC LISFEXP LISFFUN LISFPRES
                            LISBGHLP LISBGARG LISBGCRT LISBGFEL LISBGNRV




								                            LISBGCHR LISBGANG LISBGRSP LISBGEXP LISBGFUN;
	VALUE RELATE 1='NEVER' 2='SELDOM' 3='SOMETIMES' 4='FAIRLY OFTEN' 5='OFTEN';
	*Format COUNT used for the following variables: LISRELAT LISNUMCL LISFPERS












																								                                                LISCLOUT;
	VALUE COUNT 1='NONE' 2='ONE' 3='TWO' 4='THREE' 5='FOUR OR MORE';
	*Format OFTEN used for the following variables: LISRTME LISFINTH;
	VALUE OFTEN 1='NEVER' 2='LESS THAN ONCE A MONTH' 3='ONCE OR TWICE A MONTH' 
		4='ONCE A WEEK' 5='SEVERAL TIMES A WEEK';
	*Format STEP_PAR used for the following variables: LISSMOTH LISSFATH;
	VALUE STEP_PAR 1='NO' 2='YES' 3='NA';
	VALUE LISNEWSS 1='A BETTER SCHOOL' 2='NO BETTER OR WORSE THAN LAST ONE' 
		3='A WORSE SCHOOL';
	VALUE LISRELIG 1='NEVER' 2='ONCE OR TWICE A YEAR' 3='SEVERAL TIMES A YEAR' 
		4='ONCE OR TWICE A MONTH' 5='EVERY WEEK';

proc datasets library=ophase23;
	modify lisrpubn;
	Format LISNEWH LISNEWMN LISMOUT LISPRSEP LISPRDIV LISMADI LISPADI LISBSDI 
		LISMAREM LISPAREM LISSTOLE LISBURGL LISATTAK LISHOSP LISACCID LISHLTIM 
		LISMALFE LISMBTR LISMWRS LISMACC LISMHOSP LISMILL LISMLSTJ LISMWORK LISPALFE 
		LISPBTR LISPWRS LISPACC LISPHOSP LISPILL LISPLSTJ LISPWORK LISBRSIS LISSTEP 
		LISBSBTR LISBSWRS LISBSACC LISBSHSP LISBSILL LISBSBTH LISRBTR LISRWSE LISRACC 
		LISRILL LISREMOT LISRECIL LISRDIED LISRMVD LISMOTH LISMMEDC LISFATH LISFMEDC 
		LISBRSS LISSBRSS LISBSMED LIS1ADLT LISTEAM LISTRYOT LISTRBLS LISSUSCH LISHELD 
		LISAWARD LISTINFL LISSCGRP LISDROP LISNEWS LISFBTR LISFWRS LISNEWFR LISNEWBF 
		LISFDROP LISOTM LISOTRY LISFDIED LISFMVD LISSDATE LISFLOVE LISREJCT LISSTDY 
		LISBRKUP LISRELCB LISRECW LISCBGFR LISCOMM NO_YES.
        LISHOMES LISHOMES.
        LISPLIVW LISPLIVW.
        LISNEWMS LISMOUTS LISMARMS LISPARMS EVENTS.
        LISKEPTU LISSPACE LISHEAT LISCOOL LISQUIET LISSAFE LISMEDC 
		LISFDCL LISLIVE LISOTHTH LISACTET LISEXTRA ABOUT_PT.
        LISWORK LISMAWKN LISPAWKN WORK.
        LISMASCH LISPASCH SCHOOL.
        LISMHELP LISMARGU LISMCRIT LISMFEEL LISMNERV LISMCHR LISMANGR 
		LISMRSPT LISMEXP LISMFUN LISMSTRT LISMPRES LISPHELP LISPARGU LISPCRIT 
		LISPFEEL LISPNERV LISPCHR LISPANGR LISPRSPT LISPEXP LISPFUN LISPSTRT LISPPRES 
		LISBSHLP LISBSARG LISBSCRT LISBSFEL LISBSNRV LISBSCHR LISBSANG LISBSRSP 
		LISBSEXP LISBSFUN LISBSSUP LISRHELP LISRARGU LISRCRIT LISRFEEL LISRNERV 
		LISRCHR LISRANGR LISRRSPT LISREXP LISRFUN LISARGU LISCRIT LISNERVS LISANGRY 
		LISEXPCT LISSARGU LISSCRIT LISSNERV LISSANG LISSEXP LISSPRES LISTHELP 
		LISTARGU LISTCRIT LISTFEEL LISTNERV LISTCHR LISTANGR LISTRSPT LISTEXP LISTFUN 
		LISFHELP LISFARGU LISFCRIT LISFFEEL LISFNERV LISFCHR LISFANGR LISFRSPC 
		LISFEXP LISFFUN LISFPRES LISBGHLP LISBGARG LISBGCRT LISBGFEL LISBGNRV 
		LISBGCHR LISBGANG LISBGRSP LISBGEXP LISBGFUN RELATE.
        LISRELAT LISNUMCL LISFPERS LISCLOUT COUNT.
        LISRTME LISFINTH OFTEN.
        LISSMOTH LISSFATH STEP_PAR.
        LISNEWSS LISNEWSS.
        LISNEWSS LISNEWSS.;
	RUN;

proc export data=ophase23.lisrpubn 
		outfile="/home/sasuser/CSSCD/output/phase23_lisrpubn.csv";
	delimiter=',';
run;

*mra.fmt;

PROC FORMAT;
	* FORMAT NO_YES IS DEFINED FOR VARIABLES: ON_TAPE ADEQUATE COMPPREV IREP_REC
  SOURCE TARGETED UNSEGPAR COMMENTS;
	VALUE NO_YES 1='NO' 2='YES';
	* FORMAT REASON IS DEFINED FOR VARIABLES: INADREAS REJ_REAS;
	VALUE REASON 1='INCOMPLETE STUDY' 2='MOTION ARTIFACT' 3='OTHER';
	VALUE ACCEPTED 1='ACCEPTED' 2='REJECTED';
	VALUE SCANQUAL 1='EXCELLENT' 2='SLIGHT ARTIFACT/MOTION' 
		3='SEVERE ARTIFACT/MOTION - INADEQUATE';
	* FORMAT RATING IS DEFINED FOR VARIABLES: RICA_A RMCA_A RACA_A RPCA_A LICA_A
  LMCA_A LACA_A LPCA_A BASILRA;
	VALUE RATING 1='NORMAL' 2='STENOSIS - MILD' 3='STENOSIS - MODERATE' 
		4='STENOSIS - SEVERE' 5='OCCLUSION' 6='NOT ASSESSABLE' 
		7='DEPHASING ARTIFACT, LIKELY NORMAL' 
		8='CONGENITALLY ABSENT OR HYPOPLASTIC (SMALL)';
	* FORMAT $STATUS IS DEFINED FOR VARIABLES: RICA_B1 RMCA_B1
  RACA_B1 RPCA_B1 LICA_B1 LMCA_B1 LACA_B1 LPCA_B1 BASILRB1 
  RPCOA_B1 LPCOA_B1 RHBLD_B1 LHBLD_B1;
	VALUE $STATUS 'A'='IMPROVED' 'B'='SAME (NO PROGRESSION)' 
		'C'='WORSE (PROGRESSION)' 'D'='CANNOT DETERMINE' 'E'='N/A';
	* FORMAT PCOA IS DEFINED FOR VARIABLES: RPCOA_A LPCOA_A;
	VALUE PCOA 1='NORMAL' 2='SMALL' 3='NOT VISUALIZED';
	* FORMAT FLOW IS DEFINED FOR VARIABLES: RHBLD_A LHBLD_A;
	VALUE FLOW 1='GOOD' 2='POOR' 3='INDETERMINATE';
	* FORMAT REAS IS DEFINED FOR VARIABLES: REASINC REASINC2;
	VALUE REAS 1='UNSEG MIPS MISSING' 2='UNSEG MIPS WRONG' 3='SEG MIPS MISSING' 
		4='SEG MIPS WRONG' 5='UNSEG TILTS MISSING' 6='UNSEG TILTS WRONG' 7='OTHER';

proc datasets library=ophase23;
	modify mra_pubn;
	format ON_TAPE ADEQUATE COMPPREV IREP_REC SOURCE TARGETED UNSEGPAR COMMENTS 
		NO_YES.
	INADREAS REJ_REAS REASON.
	ACCEPTED ACCEPTED.
	SCANQUAL SCANQUAL.
	RICA_A RMCA_A RACA_A RPCA_A LICA_A LMCA_A LACA_A LPCA_A BASILRA RATING.
	RICA_B1 RMCA_B1 RACA_B1 RPCA_B1 LICA_B1 LMCA_B1 LACA_B1 LPCA_B1 BASILRB1 
		RPCOA_B1 LPCOA_B1 RHBLD_B1 LHBLD_B1 $STATUS.
	RPCOA_A LPCOA_A PCOA.
	RHBLD_A LHBLD_A FLOW.
	REASINC REASINC2 REAS.;
	RUN;

proc export data=ophase23.mra_pubn 
		outfile="/home/sasuser/CSSCD/output/phase23_mra_pubn.csv";
	delimiter=',';
run;

*Mrin.fmt;

PROC FORMAT;
	*Format NO_YES used for the following variables: MRIDONTP MRIACQG MRIGSUL  MRIGVENT 
                                                 MRIACQF  MRIFSUL MRIFVENT MRICBVP 







														                                                 MRICBVB   MRIOTABN;
	VALUE NO_YES 1='NO' 2='YES';
	VALUE MRIRSNP 1='ROUTINE CSSCD REQUIREMENT' 2='OTHER REASON' 3='BOTH';
	VALUE MRIORSN 1='NEW NEUROLOGICAL EVENT' 
		2='FOLLOW-UP OF OLD NEUROLOGICAL EVENT' 3='OTHER';
	VALUE MRISPNE 1='SEIZURES' 2='CVA' 3='OTHER';
	VALUE MRICVA 1='TIA' 2='OCCLUSIVE' 3='HEMORRHAGIC' 4='UNKNOWN';
	VALUE MRIIRPT 1='NOT RECEIVED' 2='RECEIVED';
	VALUE MRIQUAL 1='EXCELLENT' 2='SLIGHT ARTIFACT/MOTION, ADEQUATE' 
		3='SEVERE ARTIFACT/MOTION, INADEQUATE';
	VALUE MRIGAPP 1='NO ATROPHY' 2='ATROPHY' 3='EQUIVOCAL';
	VALUE $MRIGSEV A='MILD' B='MODERATE' C='SEVERE';
	*Format STATUS used for the following variables: MRIGSTP MRIGSTB MRIFSTP MRIFSTB;
	VALUE $STATUS A='IMPROVED' B='SAME' C='WORSE' D='CANNOT DETERMINE';
	*Format SIDE used for the following variables: MRISIDE1 MRISIDE2 MRISIDE3 MRISIDE4




								                                               MRISIDE5 MRISIDE6 MRISIDE7;
	VALUE $SIDE R='RIGHT' L='LEFT';
	*Format TYPE used for the following variables: MRITYPE1 MRITYPE2 MRITYPE3 MRITYPE4 




								                                               MRITYPE5 MRITYPE6 MRITYPE7;
	VALUE $TYPE H='HEMORRHAGE' I='INFARCT';
	*Format SIZE used for the following variables: MRISIZE1 MRISIZE2 MRISIZE3 MRISIZE4 
                                               MRISIZE5 MRISIZE6 MRISIZE7 USIZE1-USIZE12;
	VALUE SIZE 0='SMALL (PUNCTATE) (FEW MM)' 1='MEDIUM (OVOID) (0.5-1.5 CM)' 
		2='LARGE (GEOGRAPHIC) (>= 1.5 CM)';
	*Format LOCATION used for the following variables: MRILOC11 MRILOC12 MRILOC13 MRILOC14
                                                   MRILOC21 MRILOC22 MRILOC23 MRILOC24 
                                                   MRILOC31 MRILOC32 MRILOC33 MRILOC34 
                                                   MRILOC41 MRILOC42 MRILOC43 MRILOC44 
                                                   MRILOC51 MRILOC52 MRILOC53 MRILOC54
                                                   MRILOC61 MRILOC62 MRILOC63 MRILOC64 
                                                   MRILOC71 MRILOC72 MRILOC73 MRILOC74 

		                                                   ULOC1-ULOC12 UEXNT1-UEXNT12;
	VALUE LOCATION 0='FRONTAL' 1='TEMPORAL' 2='PARIETAL' 3='OCCIPITAL' 
		4='BASAL GANGLIA OR THALAMIC' 5='CORTEX' 6='CAPSULAR/CORONA' 
		7='CENTRUM SEMIOVALE' 8='BRAIN STEM' 9='CEREBELLUM';
	*Format LES_STAT used for the following variables: MRILOC1P MRILOC1B MRILOC2P MRILOC2B 
                                                   MRILOC3P MRILOC3B MRILOC4P MRILOC4B 
                                                   MRILOC5P MRILOC5B MRILOC6P MRILOC6B
                                                   MRILOC7P MRILOC7B UCMPB1-UCMPB12








																                                                   UCMPP1-UCMPP12;
	VALUE $LES_STAT A='IMPROVED' B='SAME (NO PROGRESSION)' C='WORSE (PROGRESSION)' 
		D='CANNOT DETERMINE' N='NEW LESION';
	*Format VASCULAT used for the following variables: MRIRICC MRILICC MRIRICS MRILICS MRIRMCA
                                                   MRILMCA MRIRACA MRILACA MRIRPCA MRILPCA 











																						                                                   MRIBAS;
	VALUE VASCULAT 0='NOT SEEN' 1='VISUALIZED' 2='OCCLUDED' 3='DISEASED';
	VALUE CBV 1='RIGHT' 2='LEFT' 3='BOTH' 4='NOT PRESENT';
	VALUE MRIBONE 1='NORMAL' 2='DIFFUSE THICKENING' 3='FOCAL ABNORMALITY';
	*Format BONE_CH used for the following variables: MRIBONEP MRIBONEB;
	VALUE $BONE_CH A='IMPROVED' B='SAME (NO PROGRESSION)' C='WORSE (PROGRESSION)' 
		D='CANNOT DETERMINE';
	*Format NOYESU used for following variables UBASELES--URCEREB;
	VALUE NOYESU 0='NO' 1='YES';

proc datasets library=ophase23;
	modify mri_pubn;
	format MRIDONTP MRIACQG MRIGSUL MRIGVENT MRIACQF MRIFSUL MRIFVENT MRICBVP 
		MRICBVB MRIOTABN NO_YES.
MRIRSNP MRIRSNP. MRIORSN MRIORSN. MRISPNE MRISPNE. MRICVA MRICVA. MRIIRPT 
		MRIIRPT. MRIQUAL MRIQUAL.
MRIGAPP MRIGAPP. MRIGSEV $MRIGSEV. MRIGSTP MRIGSTB MRIFSTP MRIFSTB $STATUS. 
MRISIDE1 MRISIDE2 MRISIDE3 MRISIDE4 MRISIDE5 MRISIDE6 MRISIDE7 $SIDE. 
MRILOC11 MRILOC12 MRILOC13 MRILOC14 MRILOC21 MRILOC22 MRILOC23 MRILOC24 
		MRILOC31 MRILOC32 MRILOC33 MRILOC34 MRILOC41 MRILOC42 MRILOC43 MRILOC44 
		MRILOC51 MRILOC52 MRILOC53 MRILOC54 MRILOC61 MRILOC62 MRILOC63 MRILOC64 
		MRILOC71 MRILOC72 MRILOC73 MRILOC74 ULOC1-ULOC12 UEXNT1-UEXNT12 LOCATION.
MRILOC1P MRILOC1B MRILOC2P MRILOC2B MRILOC3P MRILOC3B MRILOC4P MRILOC4B 
		MRILOC5P MRILOC5B MRILOC6P MRILOC6B MRILOC7P MRILOC7B UCMPB1-UCMPB12 
		UCMPP1-UCMPP12 $LES_STAT.
MRIRICC MRILICC MRIRICS MRILICS MRIRMCA MRILMCA MRIRACA MRILACA MRIRPCA MRILPCA 
		MRIBAS VASCULAT.
CBV CBV. MRIBONE MRIBONE. MRIBONEP MRIBONEB $BONE_CH. UBASELES--URCEREB NOYESU.;
	run;

proc export data=ophase23.mri_pubn 
		outfile="/home/sasuser/CSSCD/output/phase23_mri_pubn.csv";
	delimiter=',';
run;

*Ncvan.fmt;

PROC FORMAT;
	VALUE ID2F 10='10-VASOOCCLUSIVE PAIN' 20='20-ACUTE CHEST SYNDROME' 
		30='30-FEVER WITHOUT SOURCE' 41='41-SEPSIS' 42='42-MENINGITIS' 
		43='43-OSTEOMYELITIS' 44='44-OTHER INFECTION (SPECIFY TYPE)' 
		50='50-CNS EVENT (UNSPECIFIED)' 51='51-INFARCTIVE STROKE' 53='53-SEIZURE' 
		54='54-OTHER NEUROLOGICAL EVENT' 60='60-ACUTE ANEMIA (UNSPECIFIED)' 
		61='61-SPLENIC SEQUESTRATION' 62='62-APLASTIC CRISIS' 
		63='63-OTHER ANEMIA (SPECIFY TYPE)' 70='70-RIGHT UPPER QUADRANT' 
		80='80-PRIAPISM' 90='90-SURGERY (SPECIFY TYPE)' 100='100-NEW LEG ULCER' 
		111='111-NEW ASEPTIC NECROSIS (HIP)' 
		112='112-NEW ASEPTIC NECROSIS (SHOULDER)' 
		120='120-RENAL COMPLICATION (NOT SPECIFIED BELOW)' 
		121='121-URINARY TRACT INFECTION' 122='122-HEMATURIA' 123='123-PROTEINURIA' 
		124='124-RENAL INSUFFICIENCY' 150='150-DEATH' 
		160='160-OTHER EVENT NOT SPECIFIED' 161='161-OTHER EVENT NOT SPECIFIED';
	*Format NO_YES used for the following variables: EVW1WK EVHOSP EVBLDS EVURNS
                                                 EVTHRS EVOTHS EVSER EVASEVNT


				                                                 EVVENT EVDIE EVINFECT EVCULT;
	VALUE NO_YES 1='NO' 2='YES';
	VALUE EVSAME 1='NO' 2='YES' 9='DONT KNOW';
	VALUE EVTRANS 1='NO' 2='YES' 8='NOT APPLICABLE - EVENT DEATH';
	*Format CX_SERO used for the following variables: EVBLDR EVURNR EVTHRR EVOTHR




								                                                  EVSERR1 EVSERR2 EVSERR3;
	VALUE CX_SERO 1='NEGATIVE' 2='POSITIVE';

proc datasets library=ophase23;
	modify ncvapubn;
	FORMAT EVID2 ID2F. EVW1WK EVHOSP EVBLDS EVURNS EVTHRS EVOTHS EVSER EVASEVNT 
		EVVENT EVDIE EVNTRNSC EVINFECT EVCULT NO_YES. EVSAME EVSAME.
                EVBLDR EVURNR EVTHRR EVOTHR EVSERR1 EVSERR2 
		EVSERR3 CX_SERO.
                EVTRANS EVTRANS.;
	RUN;

proc export data=ophase23.ncvapubn 
		outfile="/home/sasuser/CSSCD/output/phase23_ncvapubn.csv";
	delimiter=',';
run;

*nen.fmt;

PROC FORMAT;
	VALUE ID2F 1='1-PH2 ENTRY VIS' 3='3-PH2 ANN 1 VIS' 5='5-PH2 ANN 2 VIS' 
		7='7-PH2 ANN 3 VIS' 9='9-PH2 ANN 4 VIS' 11='11-PH3 ENTRY VIS' 
		13='13-PH3 ANN 1 VIS' 15='15-PH3 ANN 2 VIS' 17='17-PH3 ANN 3 VIS' 
		19='19-PH3 ANN 4 VIS' 999='NEURO EVENT VISIT';
	VALUE NEPOS 1='PEDIATRIC NEUROLOGIST' 2='PEDIATRIC HEMATOLOGIST' 
		3='PA OR NURSE PRACTITIONER' 4='OTHER SPECIFY';
	VALUE NEPOSNR 0='AWAKE AND ALERT' 1='LETHARGIC' 2='CONFUSED' 3='STUPOROUS' 
		4='COMATOSE' 5='UNRESPONSIVE';
	VALUE NELNFCA 1='NO DEFICITS NOTED' 2='NRML CNVRSE,ERR COMP/EXP' 
		3='NRML CNVRSE,DIFF' 4='VRBAL COMMUNIC POSSIBLE' 5='NO VRBAL COMMUNIC' 
		6='DYSARTHRIA';
	*Format DOMINANT used for the following variables: NEDOMEYE
        NEDOMHND NEDOMFT;
	VALUE DOMINANT 1='LEFT' 2='RIGHT' 3='AMBIDEXTROUS' 4='UNDETERMINED';
	*Format CRANNERV used for the following variables: NEPUPRR NEPUPRL
        NEEXMVR NEEXMVL NEFACSR NEFACSL NEFACPR NEFACPL NEPALRR
        NEPALRL NETONGMR NETONGML NECRNRR NECRNRL NEWEBERR NEWEBERL









																		        NERINNER NERINNEL NEPLNRR NEPLNRL;
	VALUE CRANNERV 1='NORMAL' 2='ABNORMAL' 3='NOT TESTED';
	*Format PLANTAR used for the following variables: NEPLNRR NEPLNRL;
	VALUE PLANTAR 1='NORMAL' 2='ABNORMAL' 3='NOT TESTED' 4='CLONUS';
	*Format EYENERV used for the following variables: NENYGTR NENYGTL
        NENYVGR NENYVGL NEHRNSR NEHRNSL;
	VALUE EYENERV 1='PRESENT' 2='ABSENT' 3='NOT TESTED';
	*Format MUSCTONE used for the following variables: NEMSTRU NEMSTRL
        NEMSTLU NEMSTLL;
	VALUE MUSCTONE 1='NORMAL' 2='INCREASED' 3='DECREASED' 4='NOT TESTED';
	*Format MOTORPWR used for the following variables: NEMOPRU NEMOPRL
        NEMOPLU NEMOPLL;
	VALUE MOTORPWR 1='NORMAL' 2='ABNORMAL';
	*Format MTRPWLOC used for the following variables: NEMOPRUA NEMOPRLA
        NEMOPLUA NEMOPLLA;
	VALUE MTRPWLOC 1='PROXIMAL' 2='DISTAL' 3='BOTH';
	VALUE NEDRIFT 1='NO' 2='YES';
	VALUE NEDRIFTL 1='RIGHT ARM' 2='LEFT ARM' 3='BOTH ARMS';
	*Format INVOLMOV used for the following variables:NEINVRU NEINVLU
        NEINVRL NEINVLL;
	VALUE INVOLMOV 1='NO' 2='YES';
	VALUE NERMBRG 1='POSITIVE' 2='NEGATIVE' 3='NOT TESTED';
	VALUE NEGAIT 12='UNABLE TO WALK, BROAD BASED, LIMP, ATAXIC(12)' 
		16='NOT TESTED(16)' 32='NORMAL(32)';
	VALUE NELIMP 1='RIGHT' 2='LEFT' 3='BOTH';
	*Format CERFUNCT used for the following variables: NECRBFNR NECRBFNL









																		        NECRBHSR NECRBHSL NECRBRMR NECRBRML;
	VALUE CERFUNCT 1='NORMAL' 2='ABNORMAL';
	*Format REFLEX used for the following variables: NEBICR NETRICR NEULNR
        NERADR NEKNEER NEANKLR NEBICL NETRICL NEULNL NERADL NEKNEEL
        NEANKLL;
	VALUE REFLEX 1='NORMAL' 2='HYPERACTIVE' 3='ABSENT/HYPOACTIVE' 4='NOT TESTED';
	*Format CLONUS used for the following variables: NEBICRC NETRICRC NEULNRC
        NERADRC NEKNEERC NEANKLRC NEBICLC NETRICLC NEULNLC NERADLC NEKNEELC
        NEANKLLC;
	VALUE CLONUS 1='NO' 2='YES, <=3 BEATS' 3='YES, >3 BEATS' 4='NOT TESTED';
	*Format SENSORY used for the following variables: NEARMLTA NEARMRTA
        NELEGLTA NELEGRTA NETRKLTA NETRKRTA NEARMLPN NEARMRPN NELEGLPN
        NELEGRPN NETRKLPN NETRKRPN NESADLPN NESADRPN NEARMLVB NEARMRVB
        NELEGLVB NELEGRVB NETRKLVB NETRKRVB NESADLVB NESADRVB NEARMLPO
        NEARMRPO NELEGLPO NELEGRPO NETRKLPO NETRKRPO NESADLPO NESADRPO
        NESADLTA NESADRTA;
	VALUE SENSORY 1='NORMAL' 2='ABNORMAL' 3='NOT TESTED';
	* The following are Phase 2 variables;
	VALUE NEINFCT 1='NORMAL' 2='DISORIENTED' 3='INAPPROPRIATE BEHAVIOR' 
		4='NOT TESTED';
	VALUE NELNFCB 1='NO' 2='YES';
	VALUE NELNFCC 1='NO-SAME' 2='YES-WORSENED' 3='YES-IMPROVED';
	* FORMAT NO_YES is used for the following variables: NEBLINDR NEBLINDL NETRNSC;
	VALUE NO_YES 1='NO' 2='YES';

proc datasets library=ophase23;
	modify ne_pubn;
	FORMAT NEID2 ID2F. NEPOS NEPOS. NEPOSNR NEPOSNR. NELNFCA NELNFCA.
                NEDOMEYE NEDOMHND NEDOMFT DOMINANT. NEPUPRR 
		NEPUPRL NEEXMVR NEEXMVL NEFACSR NEFACSL NEFACPR NEFACPL NEPALRR NEPALRL 
		NETONGMR NETONGML NECRNRR NECRNRL NEWEBERR NEWEBERL NERINNER NERINNEL 
		CRANNERV. NEPLNRR NEPLNRL PLANTAR. NENYGTR NENYGTL NENYVGR NENYVGL NEHRNSR 
		NEHRNSL EYENERV. NEMSTRU NEMSTRL NEMSTLU NEMSTLL MUSCTONE. NEMOPRU NEMOPRL 
		NEMOPLU NEMOPLL MOTORPWR. NEMOPRUA NEMOPRLA NEMOPLUA NEMOPLLA 
		MTRPWLOC. NEDRIFT NEDRIFT. NEDRIFTL NEDRIFTL. NEINVRU NEINVLU NEINVRL NEINVLL 
		INVOLMOV. NERMBRG NERMBRG. NEGAIT NEGAIT. NELIMP NELIMP.
                NECRBFNR NECRBFNL NECRBHSR NECRBHSL NECRBRMR 
		NECRBRML CERFUNCT.
                NEBICR NETRICR NEULNR NERADR NEKNEER NEANKLR 
		NEBICL NETRICL NEULNL NERADL NEKNEEL NEANKLL REFLEX. NEBICRC NETRICRC NEULNRC 
		NERADRC NEKNEERC NEANKLRC NEBICLC NETRICLC NEULNLC NERADLC NEKNEELC NEANKLLC 
		CLONUS. NEARMLTA NEARMRTA NELEGLTA NELEGRTA NETRKLTA NETRKRTA NEARMLPN 
		NEARMRPN NELEGLPN NELEGRPN NETRKLPN NETRKRPN NESADLPN NESADRPN NEARMLVB 
		NEARMRVB NELEGLVB NELEGRVB NETRKLVB NETRKRVB NESADLVB NESADRVB NEARMLPO 
		NEARMRPO NELEGLPO NELEGRPO NETRKLPO NETRKRPO NESADLPO NESADRPO NESADLTA 
		NESADRTA SENSORY. NEINFCT NEINFCT. NELNFCB NELNFCB. NELNFCC NELNFCC.
                NEBLINDR NEBLINDL NETRNSC NO_YES.;
	RUN;

proc export data=ophase23.ne_pubn 
		outfile="/home/sasuser/CSSCD/output/phase23_ne_pubn.csv";
	delimiter=',';
run;

*npcn.fmt;

PROC FORMAT;
	* FORMAT N_Y IS DEFINED FOR VARIABLES: AGE17 NPCNE NPCTRNSC NPCABNNE;
	VALUE N_Y 1='NO' 2='YES';
	VALUE NPCHAND 1='RIGHT' 2='LEFT' 3='CANNOT BE ASSESSED';

proc datasets library=ophase23;
	modify npc_pubn;
	format AGE17 NPCNE NPCTRNSC NPCABNNE N_Y.
 	NPCHAND NPCHAND.;
	run;

proc export data=ophase23.npc_pubn 
		outfile="/home/sasuser/CSSCD/output/phase23_npc_pubn.csv";
	delimiter=',';
run;

*nppn.fmt;

PROC FORMAT;
	*Format NO_YES used for the following variables: NPPACBCO NPPACBLB NPPFESCO
                            NPPFESLB NPPMOM NPPLIVPT NPPINT NPPOLASP NPPCHMST







														                            NPPEVAL NPPSCHIN NPPTRNSC;
	VALUE NO_YES 1='NO' 2='YES';
	VALUE NPPCLAPL 1='HEAD START(1)' 2='EARLY CHILDHOOD INTERVEN PROG(2)' 
		4='REG PUBLIC SCHOOL CLASSES(4)' 8='REG PRIVATE SCHOOL CLASSES(8)' 
		16='LEARNING DISABILITIES PROG(16)' 32='EMOT/BEHAV HANDICAPPED PROG(32)' 
		64='EDUCABLE MENT-HANDICAP(64)' 128='GIFTED(128)' 
		256='HOMEBOUND TUTORING(256)' 512='COMBINATION OF ABOVE(512)' 
		1024='OTHER(1024)' 2048='NONE(2048)';
	VALUE NPPINTTY 1='INPATIENT PSYCH HOSPITAL(1)' 2='AFTER SCHOOL TUTORING(2)' 
		4='SPECIAL TUTORING PROGRAM(4)' 8='COUNSELING BY PROFESSIONAL(8)' 
		16='PHYS/SPEECH/OCCUPA THERAPY(16)' 32='OTHER(32)';
	* Format LANG used for the following variables: NPPLANG1;
	VALUE LANG 1='ENGLISH(1)' 2='SPANISH(2)' 4='FRENCH(4)' 8='CREOLE(8)' 
		16='OTHER(16)';
	VALUE NPPMARST 1='NEVER MARRIED' 2='MARRIED AND LIVING W/ SPOUSE' 3='DIVORCED' 
		4='SEPARATED' 5='WIDOWED';
	VALUE NPPLVSIT 1='LIVE WITH FATHER OF INFANT(1)' 2='LIVE WITH BOYFRIEND(2)' 
		4='LIVE WITH RELATIVE(4)' 8='LIVE ALONE(8)' 16='OTHER(16)';
	VALUE NPPED 1='LESS THAN 6 GRADES' 2='THROUGH GRADE 6' 3='THROUGH GRADE 9' 
		4='SOME HIGH SCHOOL' 5='HIGH SCHOOL/GED' 6='SOME TECHNICAL TRAINING' 
		7='COLLEGE/ASSOCIATES DEGREE' 8='BACHELORS DEGREE' 9='BEYOND BACHELORS';
	VALUE NPPEMPLY 1='NO' 2='YES - ONE JOB' 3='YES - TWO OR MORE JOBS';
	VALUE NPPMC 1='BLUE CROSS/BLUE SHIELD(1)' 2='HMO(2)' 
		4='OTHER PRIVATE INSURANCE(4)' 8='MEDICAID(8)' 
		16='ST CRIPPLED CHILDRENS PROG(16)' 32='OTHER PUBLIC PROGRAM(32)' 
		64='FAMILYS OWN FUNDS(64)' 128='OTHER(128)';
	VALUE NPPSCHDM 1='LESS THAN 7 DAYS' 2='7 TO 20 DAYS' 3='21 DAYS OR MORE';
	VALUE NPPSCISN 1='NOT RECEIVED' 2='RECEIVED';

proc datasets library=ophase23;
	modify npp_pubn;
	format NPPACBCO NPPACBLB NPPFESCO NPPFESLB NPPMOM NPPLIVPT NPPINT NPPOLASP 
		NPPCHMST NPPEVAL NPPSCHIN NPPTRNSC NO_YES.
	NPPCLAPL NPPCLAPL.
	NPPINTTY NPPINTTY.
	NPPLANG1 LANG.
	NPPMARST NPPMARST.
	NPPLVSIT NPPLVSIT.
	NPPED NPPED.
	NPPEMPLY NPPEMPLY.
	NPPMC NPPMC.
	NPPSCHDM NPPSCHDM.
        NPPSCISN NPPSCISN.;
	run;

proc export data=ophase23.npp_pubn 
		outfile="/home/sasuser/CSSCD/output/phase23_npp_pubn.csv";
	delimiter=',';
run;

*pepn.fmt;

PROC FORMAT;
	VALUE ID2F 1='1-PH2 ENTRY VIS' 3='3-PH2 ANN 1 VIS' 5='5-PH2 ANN 2 VIS' 
		7='7-PH2 ANN 3 VIS' 9='9-PH2 ANN 4 VIS' 11='11-PH3 ENTRY VIS' 
		13='13-PH3 ANN 1 VIS' 15='15-PH3 ANN 2 VIS' 17='17-PH3 ANN 3 VIS' 
		19='19-PH3 ANN 4 VIS';
	* Format NO_YES used for the following variables: PERHPLM PELHPLM
        PERSHLM PELSHLM PE_NEURO PETRNSC PERKNLM PELKNLM PERANLM 
	PELANLM PEOTHLM PEABNE;
	VALUE NO_YES 1='NO' 2='YES';
	VALUE QCFLAG 0='ENTERED, NO QC' 1='SELECTED FOR QC' 2='QC DONE';
	VALUE EFLAG 0='0-NO EDITS' 1='1-EDITS-NO UPDATE' 2='2-EDITS-SOME UPDATES' 
		3='3-EDITS-ALL UPDATED' 8='8-EDITS-NO CHANGES' 9='9-EDITS-BAD RESPONSE';

proc datasets library=ophase23;
	modify pep_pubn;
	format PEID2 ID2F.
	PERHPLM PELHPLM PERSHLM PELSHLM PE_NEURO PETRNSC PERKNLM PELKNLM PERANLM 
		PELANLM PEOTHLM PEABNE NO_YES.;
	run;

proc export data=ophase23.pep_pubn 
		outfile="/home/sasuser/CSSCD/output/phase23_pep_pubn.csv";
	delimiter=',';
run;

*pfifn.fmt;

PROC FORMAT;
	*Format NO_YES used for the following variables: PFIACS PFIARI PFIOACUT
                            PFICOOP PFIWZHX PFIASTHX PFIASMED PFISTER
                            PFISSTER PFIISTER PFIBSYM PFITHEO PFICROM
                            PFIACHOL PFIOMED PFIHSSMK PFIPCSG
                            PFITOSG PFIMEDS PFIRALES PFIRN PFIWZ PFIMBR





										                            PFIORAB PFIABLE PFIURIOR PFITRNSC;
	VALUE NO_YES 1='NO' 2='YES';
	*Format BREATHE used for the following variables: PFIDIFBR PFISNORE PFISTBR;
	VALUE BREATHE 1='NEVER' 2='OCCASIONALLY' 3='FREQUENTLY' 4='ALWAYS';

proc datasets library=ophase23;
	modify pfifpubn;
	format PFIACS PFIARI PFIOACUT PFICOOP PFIWZHX PFIASTHX PFIASMED PFISTER 
		PFISSTER PFIISTER PFIBSYM PFITHEO PFICROM PFIACHOL PFIOMED PFIHSSMK PFIPCSG 
		PFITOSG PFIMEDS PFIRALES PFIRN PFIWZ PFIMBR PFIORAB PFIABLE PFIURIOR NO_YES.
      PFIDIFBR PFISNORE PFISTBR BREATHE.;
	run;

proc export data=ophase23.pfifpubn 
		outfile="/home/sasuser/CSSCD/output/phase23_pfifpubn.csv";
	delimiter=',';
run;

*pftpn.fmt;

PROC FORMAT;
	VALUE ID2F 1='1-PH2 ENTRY VIS' 3='3-PH2 ANN 1 VIS' 5='5-PH2 ANN 2 VIS' 
		7='7-PH2 ANN 3 VIS' 9='9-PH2 ANN 4 VIS' 11='11-PH3 ENTRY VIS' 
		13='13-PH3 ANN 1 VIS' 15='15-PH3 ANN 2 VIS' 17='17-PH3 ANN 3 VIS';
	*Format NO_YES used for the following variables: PFTBRON PFTPOXDN PFTCOOX PFTRNSC;
	VALUE NO_YES 1='NO' 2='YES';
	VALUE PFTBRONT 1='0.5CC ALBUTEROL + 2CC SALINE' 
		2='METERED DOSE INHALER, ALBUTEROL';
	VALUE PFTLVMS 1='7 MIN HELIUM REBREATHING METH' 2='BODY PLETHYSMOGRAPHY' 
		3='NITROGEN WASHOUT';
	VALUE PFTTEST 1='EXCELLENT' 2='FAIR' 3='UNACCEPTABLE';

proc datasets library=ophase23;
	modify pftppubn;
	FORMAT PFTID2 ID2F.
       PFTBRON PFTPOXDN PFTCOOX PFTRNSC NO_YES.
       PFTBRONT PFTBRONT.
       PFTLVMS PFTLVMS.
       PFTTEST PFTTEST.;
	RUN;

proc export data=ophase23.pftppubn 
		outfile="/home/sasuser/CSSCD/output/phase23_pftppubn.csv";
	delimiter=',';
run;

*prlnn.fmt;

PROC FORMAT;
	* Format HOW_FEEL used for the following variables: PSMEQ PSMGQAL PSMFAIL
                           PSMDOTH PSMPROUD PSMPOSAT PSMSATIS PSMRSPCT PSMUSELS
                           PSMNOGD PSMLOOKS PSMEMB PSMNOWAY PSMPUSH PSMCNTRL



						                           PSMDOANY PSMHLPLS PSMFUTR PSMCHG;
	VALUE HOW_FEEL 1='STRONGLY AGREE' 2='AGREE' 3='DISAGREE' 4='STRONGLY DISAGREE';
	VALUE PSMTRNSC 1='NO' 2='YES';

proc datasets library=ophase23;
	modify prlnpubn;
	format PSMEQ PSMGQAL PSMFAIL PSMDOTH PSMPROUD PSMPOSAT PSMSATIS PSMRSPCT 
		PSMUSELS PSMNOGD PSMLOOKS PSMEMB PSMNOWAY PSMPUSH PSMCNTRL PSMDOANY PSMHLPLS 
		PSMFUTR PSMCHG HOW_FEEL.
	PSMTRNSC PSMTRNSC.;
	run;

proc export data=ophase23.prlnpubn 
		outfile="/home/sasuser/CSSCD/output/phase23_prlnpubn.csv";
	delimiter=',';
run;

*pvtqn.fmt;

PROC FORMAT;
	* Format NO_YES used for the following variables: PQADMIN PQACC PQTRNSC;
	VALUE NO_YES 1='NO' 2='YES';
	VALUE PQREL 1='MOTHER' 2='FATHER' 3='OTHER';
	VALUE PQHLANG 1='ENGLISH' 2='SPANISH' 3='FRENCH' 4='CREOLE' 5='OTHER';

proc datasets library=ophase23;
	modify pvtqpubn;
	format PQADMIN PQACC PQTRNSC NO_YES.
	PQREL PQREL.
	PQHLANG PQHLANG.;
	run;

proc export data=ophase23.pvtqpubn 
		outfile="/home/sasuser/CSSCD/output/phase23_pvtqpubn.csv";
	delimiter=',';
run;

*rst.fmt;

PROC FORMAT;
	VALUE HEMO 1='SS' 2='SC' 3='SB+ THAL' 4='SB0 THAL' 5='SS ALPHA THAL' 
		6='SB0 + ALPHA THAL' 7='SB0 + DELTA THAL' 8='OTHER VARIANT' 9='TRANSFUSED';
	VALUE RACE 1='BLACK' 2='OTHER';
	VALUE SEX 1='FEMALE' 2='MALE';
	VALUE PTYPE 1='FULL PROTOCOL' 2='SEMI-PROTOCOL';
	VALUE DXSOURCE 1='CDC' 2='FORM 14' 3='CLINIC EDIT';
	* Format NO_YES used for the following variables: PHASE2 PHASE3 HASTUBE
     DIED;
	VALUE NO_YES 0='NO' 1='YES';
	* NOTE: VARIABLE DIED HAS A VALUE ONLY IF PATIENT DIED - I.E., MISSING
   VALUES =NO;

proc datasets library=ophase23;
	modify rost2n3p;
	format HEMO HEMO2 HEMO.
        SEX SEX.
        RACE RACE.
        PHASE2 PHASE3 DIED NO_YES.
        DXSOURCE DXSOURCE.
        PTYPE PTYPE.;
	run;

proc export data=ophase23.rost2n3p 
		outfile="/home/sasuser/CSSCD/output/phase23_rost2n3p.csv";
	delimiter=',';
run;

*txn.fmt;

PROC FORMAT;
	* FORMAT CODE IS DEFINED FOR VARIABLES: TXRSN TXRSNCHR;
	VALUE CODE 10='VASOOCCLUSIVE PAIN' 20='ACUTE CHEST SYNDROME' 
		30='FEVER WITHOUT SOURCE' 41='SEPSIS' 42='MENINGITIS' 43='OSTEOMYELITIS' 
		50='CEREBROVASCULAR ACCIDENT' 53='SEIZURE' 60='ACUTE ANEMIA, UNSPECIFIED' 
		61='SPLENIC SEQUESTRATION' 62='APLASTIC CRISIS' 
		63='OTHER ANEMIA (SPECIFY TYPE)' 70='RIGHT UPPER QUADRANT' 80='PRIAPISM' 
		90='SURGERY (PRE-OP)' 91='SURGERY (INTRA-OP)' 92='SURGERY (POST-OP)' 
		100='LEG ULCER' 110='ASEPTIC NECROSIS' 120='RENAL COMPLICATIONS' 
		130='DELIVERY' 140='PREGNANCY' 160='OTHER (SPECIFY TYPE)';
	* FORMAT NO_YES IS DEFINED FOR VARIABLES: TXCHRN TXTRNSC;
	VALUE NO_YES 1='NO' 2='YES';
	VALUE TXTYPE 1='SIMPLE' 2='PARTIAL EXCHANGE' 3='EXCHANGE';

proc datasets library=ophase23;
	modify tx_pubn;
	format TXRSN TXRSNCHR CODE. 
	TXCHRN TXTRNSC NO_YES.
        TXTYPE TXTYPE.;
	run;
proc export data=ophase23.tx_pubn 
		outfile="/home/sasuser/CSSCD/output/phase23_tx_pubn.csv";
	delimiter=',';
run;