*Manual decoding and curation for CSSCD;
libname phase2a "/home/sasuser/CSSCD/Phase2A/SAS_Data";
libname uphase2 '/home/sasuser/CSSCD/phase2ameta';

proc copy inlib=phase2a outlib=uphase2 noclone datecopy;
run;

proc export data=uphase2.hapdata 
		outfile="/home/sasuser/CSSCD/output/phase2a_hapdata.csv";
	delimiter=',';
run;

*LABA.FMT;

data uphase2.labadata;
	set uphase2.labadata;
	ARRAY NEGCODES LABTRANS LABCBCWB--LABPLATE LABALKPH--URPROMGD LABCRTN2 LABIRPT;

	DO OVER NEGCODES;

		IF NEGCODES EQ -9 THEN
			NEGCODES=.;

		IF NEGCODES EQ -1 THEN
			NEGCODES=.A;

		IF NEGCODES EQ -8 THEN
			NEGCODES=.B;

		IF NEGCODES EQ -7 THEN
			NEGCODES=.C;
	END;
	ARRAY NEGDATES LABDATE LABDATE2 LABDATE3;

	DO OVER NEGDATES;

		IF NEGDATES EQ MDY(9, 9, 9) THEN
			NEGDATES=.;

		IF NEGDATES EQ MDY(1, 1, 1) THEN
			NEGDATES=.A;

		IF NEGDATES EQ MDY(8, 8, 8) THEN
			NEGDATES=.B;

		IF NEGDATES EQ MDY(11, 11, 11) THEN
			NEGDATES=.C;
	END;

PROC FORMAT;
	* FORMAT NOYES is defined for variable LABTRANS
    and LABIRPT;
	VALUE NOYES 1='1-NO' 2='2-YES'
     .='MISSING'
     .A='MISSING,REASON'
     .B='OUT-OF-RANGE'
     .C='NOT APPLICABLE';

proc datasets library=uphase2;
	modify labadata;
	format LABTRANS LABIRPT NOYES.;
	run;

proc export data=uphase2.labadata 
		outfile="/home/sasuser/CSSCD/output/phase2a_labadata.csv";
	delimiter=',';
run;

*MUGA.FMT;

data uphase2.mugadata;
	set uphase2.mugadata;
	ARRAY NEGCODES MUREQ MULVEF--MUPLW;

	DO OVER NEGCODES;

		IF NEGCODES EQ -9 THEN
			NEGCODES=.;

		IF NEGCODES EQ -1 THEN
			NEGCODES=.A;

		IF NEGCODES EQ -8 THEN
			NEGCODES=.B;

		IF NEGCODES EQ -7 THEN
			NEGCODES=.C;
	END;
	ARRAY NEGDATES MUDATE ADD_DATE;

	DO OVER NEGDATES;

		IF NEGDATES EQ MDY(9, 9, 9) THEN
			NEGDATES=.;

		IF NEGDATES EQ MDY(1, 1, 1) THEN
			NEGDATES=.A;

		IF NEGDATES EQ MDY(8, 8, 8) THEN
			NEGDATES=.B;

		IF NEGDATES EQ MDY(11, 11, 11) THEN
			NEGDATES=.C;
	END;
	ARRAY TEXTNEGS MUREQMIS MUREQST MUREQRSN;

	DO OVER TEXTNEGS;

		IF TEXTNEGS EQ '-9' THEN
			TEXTNEGS='.';

		IF TEXTNEGS EQ '-7' THEN
			TEXTNEGS='.C';

		IF TEXTNEGS EQ '-1' THEN
			TEXTNEGS='.A';

		IF TEXTNEGS EQ '-8' THEN
			TEXTNEGS='.B';
	END;

PROC FORMAT;
	* FORMAT NOYES is defined for variables MUREQ;
	VALUE NOYES 1='1-NO' 2='2-YES'
             .='MISSING'
             .A='MISSING,REASON'
             .B='OUT-OF-RANGE'
             .C='NOT APPLICABLE';
	* FORMAT MOTION is defined for variable wall motion variables MUALW MUAPW
   MUIW MUSW MUAIW MUPLW;
	VALUE MOTION 1='1-NORMAL' 2='2-HYPOKINETIC' 3='3-DYSKINETIC'
             .='MISSING'
            .A='MISSING,REASON'
            .B='OUT-OF-RANGE'
            .C='NOT APPLICABLE';

proc datasets library=uphase2;
	modify mugadata;
	format MUREQ NOYES. MUALW MUAPW MUIW MUSW MUAIW MUPLW MOTION.;
	run;

proc export data=uphase2.mugadata 
		outfile="/home/sasuser/CSSCD/output/phase2a_mugadata.csv";
	delimiter=',';
run;

*NEA.FMT;

data uphase2.neadata;
	set uphase2.neadata;
	ARRAY NEGCODES NEINFCT--NELNFCB NELNFCBC--NESADRPO;

	DO OVER NEGCODES;

		IF NEGCODES EQ -9 THEN
			NEGCODES=.;

		IF NEGCODES EQ -1 THEN
			NEGCODES=.A;

		IF NEGCODES EQ -8 THEN
			NEGCODES=.B;

		IF NEGCODES EQ -7 THEN
			NEGCODES=.C;
	END;
	ARRAY TXTNEGS NELNFCBT;

	DO OVER TXTNEGS;
		*IF NEGCODES EQ -9 THEN NEGCODES=.;
		*IF NEGCODES EQ -1 THEN NEGCODES=.A;
		*IF NEGCODES EQ -8 THEN NEGCODES=.B;

		IF TXTNEGS EQ '-7' THEN
			TXTNEGS='NOT APPLICABLE';
	END;

PROC FORMAT;
	*FOR WEBER--RINNE;
	VALUE MISS	.='MISSING'
            .A='MISSING,REASON'
        	.B='OUT-OF-RANGE'
	      .C='NOT APPLICABLE';
	* FORMAT NOYES IS DEFINED FOR VARIABLES NELNFCB, NEBLINDR, NEBLINDL,
	NEINVRU, NEINVLU, NEINVRL, NEINVLL;
	VALUE NOYES 1='1-NO' 2='2-YES'
	.='MISSING'
	.A='MISSING,REASON'
	.B='OUT-OF-RANGE'
	.C='NOT APPLICABLE';
	* FORMAT NORABNT IS DEFINED FOR VARIABLES NEVSACR, NEVSACL, NEPUPRR,
	NEPUPRL, NEEXMVR, NEEXMVL, NECRNRR, NECRNRL, NEFACSR, NEFACSL,
	NEFACPR, NEFACPL, NEPALRR, NEPALRL, NETONGMR, NETONGML, NEARMLPN,
	NEARMLTA, NEARMLVB, NEARMLPC, NEARMRPN, NEARMRTA, NEARMRVB,
	NEARMRPO, NELEGLPN, NELEGLTA, NELEGLVB, NELEGLPC, NELEGRPN, 
	NELEGRTA, NELEGRVB, NELEGRPO, NETRKLPN, NETRKLTA, NETRKLVB,
	NETRKLPO, NETRKRPN, NETRKRTA, NETRKRVB, NETRKRPO, NESADLPN,
	NESADLTA, NESADLVB, NESADLPO, NESADRPN, NESADRTA, NESADRVB,
	NESADRPO;
	VALUE NORABNT 1='1-NORMAL' 2='2-ABNORMAL' 3='3-NOT TESTED'
	.='MISSING'
	.A='MISSING,REASON'
	.B='OUT-OF-RANGE'
	.C='NOT APPLICABLE';
	* FORMAT PRESABS IS DEFINED FOR VARIABLES NENYGTR, NENYGTL, NENYVGR,
	 NENYVGL, NEHRNSR, NEHRNSL;
	VALUE PRESABS 1='1-PRESENT' 2='2-ABSENT'
	.='MISSING'
	.A='MISSING,REASON'
	.B='OUT-OF-RANGE'
	.C='NOT APPLICABLE';
	* FORMAT NORMAB IS DEFINED FOR VARIABLES NEMOPRU, NEMOPRL, NEMOPLU, 







															NEMOPLL,NECRBFNR, NECRBFNL, NECRBHSR, NECRBHSL, NECRBRMR, NECRBRML;
	VALUE NORMAB 1='1-NORMAL' 2='2-ABNORMAL'
	.='MISSING'
	.A='MISSING,REASON'
	.B='OUT-OF-RANGE'
	.C='NOT APPLICABLE';
	* FORMAT NOHYAB IS DEFINED FOR VARIABLES NEBICR, NETRICR, NEULNR, 
	NERADR, NEKNEER, NEANKLR, NEBICL, NETRICL, NEULNL, NERADL,
	NEKNEEL, NEANKLL;
	VALUE NOHYAB 1='1-NORMAL' 2='2-HYPERACTIVE' 3='3-ABSENT/HYPOACT'
	.='MISSING'
	.A='MISSING,REASON'
	.B='OUT-OF-RANGE'
	.C='NOT APPLICABLE';
	* FORMAT NOINDE IS DEFINED FOR VARIABLES NEMSTRU, NEMSTRL, NEMSTLU,
	NEMSTLL;
	VALUE NOINDE 1='1-NORMAL' 2='2-INCREASED' 3='3-DECREASED'
	.='MISSING'
	.A='MISSING,REASON'
	.B='OUT-OF-RANGE'
	.C='NOT APPLICABLE';
	* FORMAT PRODIS IS DEFINED FOR VARIABLES NEMOPRUA, NEMOPRLA, 
	NEMOPLUA, NEMOPLLA;
	VALUE PRODIS 1='1-PROXIMAL' 2='2-DISTAL' 3='3-BOTH'
	.='MISSING'
	.A='MISSING,REASON'
	.B='OUT-OF-RANGE'
	.C='NOT APPLICABLE';
	* FORMAT NOABCL IS DEFINED FOR VARIABLES NEPLNRR, NEPLNRL;
	VALUE NOABCL 1='1-NORMAL' 2='2-ABNORMAL' 3='3-CLONUS'
	.='MISSING'
	.A='MISSING,REASON'
	.B='OUT-OF-RANGE'
	.C='NOT APPLICABLE';
	* FORMAT T1X IS DEFINED FOR VARIABLE NEINFCT;
	VALUE T1X 1='1-NORMAL' 2='2-DISORIENTED' 3='3-INAPP BEHAVIOR' 4='4-NOT TESTED'
	.='MISSING'
	.A='MISSING,REASON'
	.B='OUT-OF-RANGE'
	.C='NOT APPLICABLE';
	* FORMAT T2X IS DEFINED FOR VARIABLE NELNFCA;
	VALUE T2X 1='1-NO DEFICITS' 2='2-NORM CONV POSS' 3='3-NORM CONV DIFF' 
		4='4-SOME VERB COMM' 5='5-NO VERB COMM' 6='6-DYSARTHRIA'
	.='MISSING'
	.A='MISSING,REASON'
	.B='OUT-OF-RANGE'
	.C='NOT APPLICABLE';
	* FORMAT T3X IS DEFINED FOR VARIABLE NELNFCCL;
	VALUE T3X 1='1-NO-SAME' 2='2-YES-WORSENED' 3='3-YES-IMPROVED'
	.='MISSING'
	.A='MISSING,REASON'
	.B='OUT-OF-RANGE'
	.C='NOT APPLICABLE';
	* FORMAT T4X IS DEFINED FOR VARIABLE NERMBRG;
	VALUE T4X 1='1-POSITIVE' 2='2-NEGATIVE'
	.='MISSING'
	.A='MISSING,REASON'
	.B='OUT-OF-RANGE'
	.C='NOT APPLICABLE';
	* FORMAT T5X IS DEFINED FOR VARIABLE NEGAIT;
	VALUE T5X 1='1-NORMAL' 2='2-UNABLE TO WALK' 4='3-BROAD BASED' 8='4-LIMP' 
		12='BROAD BASED+LIMP' 16='5-ATAXIC' 32='6-NOT TESTED'
	.A='MISSING,REASON';
	* FORMAT T6X IS DEFINED FOR VARIABLE NELIMP;
	VALUE T6X 1='1-RIGHT' 2='2-LEFT'
	.='MISSING'
	.A='MISSING,REASON'
	.B='OUT-OF-RANGE'
	.C='NOT APPLICABLE';

proc datasets library=uphase2;
	modify neadata;
	format WEBERR WEBERL RINNER RINNEL MISS.
NELNFCB NEBLINDR NEBLINDL NEINVRU NEINVLU NEINVRL NEINVLL NOYES.
	NEVSACR NEVSACL NEPUPRR NEPUPRL NEEXMVR NEEXMVL NECRNRR NECRNRL NEFACSR 
		NEFACSL NEFACPR NEFACPL NEPALRR NEPALRL NETONGMR NETONGML NEARMLPN NEARMLTA 
		NEARMLVB NEARMLPC NEARMRPN NEARMRTA NEARMRVB NEARMRPO NELEGLPN NELEGLTA 
		NELEGLVB NELEGLPC NELEGRPN NELEGRTA NELEGRVB NELEGRPO NETRKLPN NETRKLTA 
		NETRKLVB NETRKLPO NETRKRPN NETRKRTA NETRKRVB NETRKRPO NESADLPN NESADLTA 
		NESADLVB NESADLPO NESADRPN NESADRTA NESADRVB NESADRPO NORABNT.
	NENYGTR NENYGTL NENYVGR NENYVGL NEHRNSR NEHRNSL PRESABS.
	NEMOPRU NEMOPRL NEMOPLU NEMOPLL NECRBFNR NECRBFNL NECRBHSR NECRBHSL NECRBRMR 
		NECRBRML NORMAB.
	NEBICR NETRICR NEULNR NERADR NEKNEER NEANKLR NEBICL NETRICL NEULNL NERADL 
		NEKNEEL NEANKLL NOHYAB.
	NEMSTRU NEMSTRL NEMSTLU NEMSTLL NOINDE.
	NEMOPRUA NEMOPRLA NEMOPLUA NEMOPLLA PRODIS.
	NEPLNRR NEPLNRL NOABCL.
	NEINFCT T1X.
	NELNFCA T2X.
	NELNFCCL T3X.
	NERMBRG T4X.
	NEGAIT T5X.
	NELIMP T6X.;
	run;

proc export data=uphase2.neadata 
		outfile="/home/sasuser/CSSCD/output/phase2a_neadata.csv";
	delimiter=',';
run;

*PEA.FMT;

data uphase2.peadata;
	set uphase2.peadata;
	ARRAY NEGCODES PEPULSE--PEOTNRAB PERHPLM--PEOTHLM PEJNPR PELU PEABNE;

	DO OVER NEGCODES;

		IF NEGCODES EQ -9 THEN
			NEGCODES=.;

		IF NEGCODES EQ -1 THEN
			NEGCODES=.A;

		IF NEGCODES EQ -8 THEN
			NEGCODES=.B;

		IF NEGCODES EQ -7 THEN
			NEGCODES=.C;
	END;
	ARRAY TXTNEGS PENRAB PEEXLM;

	DO OVER TXTNEGS;

		IF TXTNEGS EQ '-7' THEN
			TXTNEGS='N/A';

		IF TXTNEGS EQ '-9' THEN
			TXTNEGS='MISSING';
	END;

PROC FORMAT;
	* FORMAT NOYES is defined for variables RALES, RONCHI, WHEEZING,
        PECHDFM, PERTMAB, PEHRMRM, PERUB, PEGLP, PEOTNRAB,
        PERHPLM, PELHPLM,PERKNLM, PELKNLM, PERSHLM, PELSHLM,
        PERANLM, PELANLM, PEOTHLM, PEJNPR, 
        PELU, PEABNE;
	VALUE NOYES 1='1-NO' 2='2-YES'
                .='MISSING'
                .A='MISSING,REASON'
                .B='OUT-OF-RANGE'
                .C='NOT APPLICABLE';
	* FORMAT MINUS IS DEFINED VOR VARIABLES PELVRSZ & PESPLTP;
	VALUE MINUS     .='MISSING'
                .A='MISSING,REASON'
                .B='OUT-OF-RANGE'
                .C='NOT APPLICABLE';

proc datasets library=uphase2;
	modify peadata;
	format RALES RHONCHI WHEEZING PECHDFM PERTMAB PEHRMRM PERUB PEGLP PEOTNRAB 
		PERHPLM PELHPLM PERKNLM PELKNLM PERSHLM PELSHLM PERANLM PELANLM PEOTHLM 
		PEJNPR PELU PEABNE NOYES.
       PELVRSZ PESPLTP MINUS.;
	run;

proc export data=uphase2.peadata 
		outfile="/home/sasuser/CSSCD/output/phase2a_peadata.csv";
	delimiter=',';
run;

*PFT.FMT;

data uphase2.pftdata;
	set uphase2.pftdata;
	ARRAY NEGCODES PFTFVC--PFTIRPT;

	DO OVER NEGCODES;

		IF NEGCODES EQ -9 THEN
			NEGCODES=.;

		IF NEGCODES EQ -1 THEN
			NEGCODES=.A;

		IF NEGCODES EQ -8 THEN
			NEGCODES=.B;

		IF NEGCODES EQ -7 THEN
			NEGCODES=.C;
	END;
	*ARRAY TXTNEGS;
	*DO OVER TXTNEGS;
	*IF TXTNEGS EQ '-7' OR TXTNEGS LT 'A' THEN TXTNEGS='NOT APPLICABLE';
	*END;

PROC FORMAT;
	* FORMAT ID2F IS DEFINED FOR VARIABLE PFTID2;
	VALUE ID2F 1='1-ENTRY PERIOD PFT' 5='5-EXIT PERIOD PFT';
	* FORMAT LUNGVOL IS DEFINED FOR VARIABLE PFTLVMS;
	VALUE LUNGVOL 1='1 - 7-MIN HELIUM REBREATHING METHOD' 
		2='2 - BODY PLETHYSMOGRAPHY' 3='3 - NITROGEN WASHOUT'
              .='MISSING'
              .A='MISSING WITH REASON'
              .B='OUT-OF-RANGE'
              .C='NOT APPLICABLE';
	* FORMAT NOYES IS DEFINED FOR VARIABLES PFTIRPT & REMARKS;
	VALUE NOYES 1='1 - NO' 2='2 - YES'
              .='MISSING'
              .A='MISSING WITH REASON'
              .B='OUT-OF-RANGE'
              .C='NOT APPLICABLE';
	* FORMAT QCFLAG IS DEFINED FOR VARIABLE QCFLAG;
	VALUE QCFLAG 0='ENTERED, NO QC' 1='SELECTED FOR QC' 2='QC DONE';

proc datasets library=uphase2;
	modify pftdata;
	format PFTID2 ID2F.
PFTLVMS LUNGVOL.
PFTIRPT REMARKS NOYES.
QCFLAG QCFLAG.;
	run;

proc export data=uphase2.pftdata 
		outfile="/home/sasuser/CSSCD/output/phase2a_pftdata.csv";
	delimiter=',';
run;

*ROST.fmt;

data uphase2.rost;
	set uphase2.rost;
	ARRAY NEGCODES RESNTFOL;

	DO OVER NEGCODES;

		IF NEGCODES EQ -9 THEN
			NEGCODES=.;

		IF NEGCODES EQ -1 THEN
			NEGCODES=.A;

		IF NEGCODES EQ -8 THEN
			NEGCODES=.B;

		IF NEGCODES EQ -7 THEN
			NEGCODES=.C;
	END;
	ARRAY TXTNEGS OTHREAS;

	DO OVER TXTNEGS;

		IF TXTNEGS EQ '-7' THEN
			TXTNEGS='N/A';

		IF TXTNEGS EQ '-9' THEN
			TXTNEGS='MISSING';
	END;
	ARRAY NEGDATES DLS DTHDATE DTKNWALV LASTPE;

	DO OVER NEGDATES;

		IF NEGDATES EQ MDY(9, 9, 9) THEN
			NEGDATES=.;

		IF NEGDATES EQ MDY(1, 1, 1) THEN
			NEGDATES=.A;

		IF NEGDATES EQ MDY(8, 8, 8) THEN
			NEGDATES=.B;

		IF NEGDATES EQ MDY(11, 11, 11) THEN
			NEGDATES=.C;
	END;
	ARRAY DOTS HEMO RACE;

	DO OVER DOTS;

		IF DOTS LT 0 THEN
			DOTS=.;
	END;

PROC FORMAT;
	*  FORMAT ANN IS DEFINED FOR VARIABLES ANN1 & ANN2;
	VALUE ANN 1='1-NOT DONE, ? REASON' 2='2-DONE' 3='3-DIED' 4='4-MOVED' 
		5='5-LTFU' 6='6-REFUSING' 7='7-TOO ILL' 8='8-BROKE APPTS' 9='9-OTHER';
	*  FORMAT NOYES IS DEFINED FOR VARIABLES DIED & PATFOLL;
	VALUE NOYES 1='1-NO' 2='2-YES';
	*  FORMAT HEMO IS DEFINED FOR VARIABLE HEMO;
	VALUE HEMO 1='1-SS' 2='2-SC' 3='3-S B+ THAL' 4='4-S B0 THAL' 5='5-SS ALPHA' 
		6='6-SB0 + ALPHA THAL' 7='7-SB0 + DELTA THAL' 8='8-OTHER VARIANT' 
		9='9-NO CDC DX';
	*  FORMAT P2ENTRY IS DEFINED FOR VARIABLE P2ENTRY;
	VALUE P2ENTRY 1='1-YES' 3='3-NO, DIED BEF 7/91' 4='4-NO, MOVED' 5='5-NO, LTFU' 
		6='6-NO, REFUSING' 8='8-NO, OTHER';
	* FORMAT PATALIVE IS DEFINED FOR VARIABLE PATALIVE;
	VALUE PATALIVE 1='1-NO' 2='2-YES' 9='9-DONT KNOW';
	*  FORMAT RACE IS DEFINED FOR VARIABLE RACE;
	VALUE RACE 1='1-BLACK' 2='2-OTHER';
	*  FORMAT RESNTFOL IS DEFINED FOR VARIABLE RESNTFOL;
	VALUE RESNTFOL 3='3-DIED' 4='4-MOVED' 5='5-LTFU' 6='6-REFUSING' 
		7='7-CHRON CARE FACIL.' 8='8-NON-COMPLIANT' 9='9-OTHER REASON';
	*  FORMAT SEX IS DEFINED FOR VARIABLE SEX;
	VALUE SEX 1='1-FEMALE' 2='2-MALE';
	*  FORMAT STATUS IS DEFINED FOR VARIABLE STATUS;
	VALUE STATUS 1='1-ACTIVE AT END OF PHASE 1' 3='3-LTFU BY END OF PHASE 1' 
		5='5-DIED BY END OF PHASE 1';

proc datasets library=uphase2;
	modify rost;
	format ANN1 ANN2 ANN.
DIED PATFOLL NOYES.
HEMO HEMO.
P2ENTRY P2ENTRY.
PATALIVE PATALIVE.
RACE RACE.
RESNTFOL RESNTFOL.
SEX SEX.
STATUS STATUS.;
	run;

proc export data=uphase2.rost 
		outfile="/home/sasuser/CSSCD/output/phase2a_rost.csv";
	delimiter=',';
run;

*CSTAT.fmt;

data uphase2.statdata;
	set uphase2.statdata;
	ARRAY NEGCODES STALIVE STMOVE STCADDR STCPHON STDTHF STFUCL STREFSL STEPE 
		STEPERSN STVISNO STCLINC;

	DO OVER NEGCODES;

		IF NEGCODES EQ -9 THEN
			NEGCODES=.;

		IF NEGCODES EQ -1 THEN
			NEGCODES=.A;

		IF NEGCODES EQ -8 THEN
			NEGCODES=.B;

		IF NEGCODES EQ -7 THEN
			NEGCODES=.C;
	END;
	ARRAY TXTNEGS STPFT STMUGA STEXER STECHO;

	DO OVER TXTNEGS;

		IF TXTNEGS EQ '-9' THEN
			TXTNEGS='.';

		IF TXTNEGS EQ '-1' THEN
			TXTNEGS='.A';

		IF TXTNEGS EQ '-8' THEN
			TXTNEGS='.B';

		IF TXTNEGS EQ '-7' THEN
			TXTNEGS='.C';
	END;

PROC FORMAT;
	* FORMAT NOYES is defined for variables STMOVE STCADDR, STCPHON, STALIVE,
  STFUCL, STDTHF, STREFSL;
	VALUE NOYES 1='1-NO' 2='2-YES' 3='NO PNONE' 9='DONT KNOW'
                .='MISSING'
                .A='MISSING,REASON'
                .B='OUT-OF-RANGE'
                .C='NOT APPLICABLE';
	* FORMAT NYES is defined for variables STEPE;
	VALUE NYES 1='1-NO' 2='2-YES'
               .='NOT ASKED'
               .A='MISSING,REASON'
               .B='OUT-OF-RANGE'
               .C='NOT APPLICABLE';
	*FORMAT MISS IS DEFINED FOR VARIABLES;
	VALUE MISS   .='MISSING'
            .A='MISSING, REASON'
            .C='NOT APPLICABLE';
	*FORMAT MISS IS DEFINED FOR THE VARIABLE STVISNO;
	VALUE VISNO  .='NOT ASKED'
             .A='MISSING, REASON'
             .C='NOT APPLICABLE';
	*SPECIAL TESTS STATUS LABELS TO MATCH STE CODES--FORMAT $LSPECST IS DEFINED FOR VARIABLES STPFT STMUGA STEXER STECHO;
	VALUE $LSPECST 'A'='A-DONE' 'B'='B-SCHEDULED' 'C'='C-REFUSED' 
		'D'='D-DISABILITY' 'E'='E-NOT DONE, OTHR RSN' '.'='MISSING' 
		'.A'='MISSING, REASON' '.C'='NOT APPLICABLE';
	* FORMAT RSN IS DEFINED FOR THE VARIABLE STEPERSN;
	VALUE RSN 1='PT MOVED' 2='PT REFUSING' 3='PARENT/G REFUSING' 
		4='PT IN NRSING HOME' 5='PT TOO ILL FOR VST' 6='PT MISSED VST-OTHRSN' 
		7='LOST TO FU' 8='LOST-NO ADDR' 9='PT DIED' 10='OTHER RSN'
          .='NOT ASKED'
         .A='MISSING,REASON'
         .B='OUT-OF-RANGE'
         .C='NOT APPLICABLE';

proc datasets library=uphase2;
	modify statdata;
	format STMOVE STCADDR STCPHON STALIVE STFUCL STDTHF STREFSL NOYES.
	STEPE NYES.
STVISNO VISNO.
STPFT STMUGA STEXER STECHO $LSPECST.
STEPERSN RSN.;
	run;

proc export data=uphase2.statdata 
		outfile="/home/sasuser/CSSCD/output/phase2a_statdata.csv";
	delimiter=',';
run;

*EVTA.FMT;

data uphase2.evtadata;
	set uphase2.evtadata;
	ARRAY NEGCODES EVID2 EVW1WK--EVHOSP EVASEVNT--EVCULT EVORGC EVTRANS;

	DO OVER NEGCODES;

		IF NEGCODES EQ -9 THEN
			NEGCODES=.;

		IF NEGCODES EQ -1 THEN
			NEGCODES=.A;

		IF NEGCODES EQ -8 THEN
			NEGCODES=.B;

		IF NEGCODES EQ -7 THEN
			NEGCODES=.C;
	END;
	ARRAY TXTNEGS EVORGN EVCULTFR;

	DO OVER TXTNEGS;

		IF TXTNEGS EQ '-7' THEN
			TXTNEGS='N/A';

		IF TXTNEGS EQ '-8' THEN
			TXTNEGS='OUT-OF-RANGE';

		IF TXTNEGS EQ '-9' THEN
			TXTNEGS='MISSING,NO RSN';

		IF TXTNEGS EQ '-1' THEN
			TXTNEGS='MISSING, WITH RSN';
	END;
	ARRAY NEGDATES EVDATE EVADMDTE EVDISDT;

	DO OVER NEGDATES;

		IF NEGDATES EQ MDY(9, 9, 9) THEN
			NEGDATES=.;

		IF NEGDATES EQ MDY(1, 1, 1) THEN
			NEGDATES=.A;

		IF NEGDATES EQ MDY(8, 8, 8) THEN
			NEGDATES=.B;

		IF NEGDATES EQ MDY(11, 11, 11) THEN
			NEGDATES=.C;
	END;

PROC FORMAT;
	*FORMAT EVID2L IS DEFINED FOR VARIABLE EVID2;
	VALUE EVID2L 10='PAIN' 20='ACUTE CHEST' 30='FEVER W/OUT SOURCE' 41='SEPSIS' 
		42='MENINGITIS' 43='OSTEOMYELITIS' 44='OTH INFECTION' 50='CNS EVNT-UNSPEC' 
		51='OCCLUSIVE STROKE' 52='HEMORRHAGIC STROKE' 53='SEIZURE' 
		54='OTH CNS EVNT-SPECIFIED' 60='ACUTE ANEMIA' 61='SEQUESTRATION' 
		62='APLASTIC' 63='OTH ANEMIA' 70='RIGHT UPPER QUADRANT' 80='PRIAPISM' 
		90='SURGERY' 100='NEW LEG ULCER' 110='NEW ASEPTIC NECROSIS' 111='HIP' 
		112='SHOULDER' 120='RENAL COMPLICATION' 121='URINARY TRACT INFECTION' 
		122='HEMATURIA' 123='PROTEINURIA' 124='RENAL INSUFFICIENCY' 130='DELIVERY' 
		140='PREGNANCY COMPLICATIONS' 150='DEATH' 160='OTHER EVENT'
.='MISSING'
.A='MISSING WITH REASON'
.B='OUT-OF-RANGE'
.C='NOT APPLICABLE';
	*FORMAT NOYES IS DEFINED FOR VARIABLES EVW1WK EVSAME EVHOSP EVASEVNT EVINFECT
  EVCULT EVTRANS;
	VALUE NOYES 1='1-NO' 2='2-YES' 8='8-N/A (EVENT DTH)' 9='9-DK'
            .='MISSING'
           .A='MISSING WITH REASON'
           .B='OUT-OF-RANGE'
           .C='NOT APPLICABLE';
proc datasets library=uphase2;
modify evtadata;
format EVID2 EVID2L.
EVW1WK EVSAME EVHOSP EVASEVNT EVINFECT EVCULT EVTRANS NOYES.;
run;
proc export data=uphase2.evtadata 
		outfile="/home/sasuser/CSSCD/output/phase2a_evtadata.csv";
	delimiter=',';
run;

