---
title: "TEMPLATE Metadata Curation"
author: "Michael Corace"
date: "N/A"
output: html_document
---

Libraries
```{r}
library(jsonlite)
library(tidyverse)
install.packages("readxl")
library(readxl)
library(dplyr)
library(stringr)
library(jsonlite)
```

Fill out inputs for the study
```{r}
phs=''
v=1
p=1
shortname=''
fullname=''
dd_filepath=""
data_files_list=c()
#variable_level_data_list=c()
consents_list=c('')
focus=''
design=''
assosciated_studies=' '
additional_info=' '
harmonized=''
study_type=''
gen3_project_name=''
new_up=""
s3_folder=""
synthetic="Synthetic"
```

```{r}

dd_raw <- read_csv(dd_filepath, show_col_types = F)


renamed_df <-  data.frame(
                            form_group="N/A",
                            form=dd_raw$table,
                            form_name= dd_raw$table,
                            form_description= "N/A",
                            variable_id=toupper(dd_raw$varname),
                            variable_type=dd_raw$type,
                            variable_group_name='NA',
                            variable_group_description="N/A",
                            variable_description=dd_raw$vardesc,
                            variable_name=dd_raw$vardesc,
                            Units=dd_raw$units
                            )
```


Json
```{r}
# Heirarchy tree
  trees_vector <- vector(mode = "character",length = length(renamed_df$variable_id))

  for (i in c(1:length(renamed_df$variable_id))) {
    study <- shortname
    
    form <- str_replace_all(renamed_df$form[i],"/","-")
     
    variable <- str_replace_all(renamed_df$variable_name[i],"/","-")
    
    tree <- paste0(study, "/",form, "/",variable)

    trees_vector[i] <- tree
  }  

  full_df <- cbind(renamed_df, trees_vector)
  names(full_df)[names(full_df) == 'trees_vector'] <- 'data_hierarchy'

# Var information level
  variable_info_df <- data.frame(
    full_df %>%
      select(
        form_group,
        form,
        form_description,
        form_name,
        variable_group_name,
        variable_group_description,
        variable_id,
        variable_name,
        variable_type,
        data_hierarchy,
        variable_description,
        Units
      ) %>%
      unique()
  )
  rownames(variable_info_df) <- NULL



  for (ind in c(1:nrow(variable_info_df))) {
    temp_df <- data.frame(full_df[ind,] %>% #$variable_description
                  select(
                    Units
                   )
                )
    
    temp_df<-temp_df %>% mutate_all(na_if,"")
    
    variable_info_df[ind, "derived_variable_level_data"][[1]] <- list(temp_df)
  }
  
  # Var level
  variable_df <- data.frame(
    variable_info_df %>%
      select(
        form_group,
        form,
        form_description,
        form_name,
        variable_group_name,
        variable_group_description
      ) %>%
      unique()
  )
  rownames(variable_df) <- NULL


  for (ind in c(1:nrow(variable_df))) {
    temp_df <- variable_info_df %>%
      filter(form == variable_df[ind, "form"], variable_group_name == variable_df[ind, "variable_group_name"]) %>%
      select(variable_id, 
            variable_name, 
            variable_type,
            variable_description,
            data_hierarchy, 
            derived_variable_level_data)
    variable_df[ind, "variable"][[1]] <- list(temp_df)
  }
  
  # Var group level
  variable_group_df <- data.frame(variable_df %>%
                                    select(form_group, form, form_name, form_description) %>%
                                    unique())
  rownames(variable_group_df) <- NULL
  

  for (ind in c(1:nrow(variable_group_df))) {
    temp_df <- variable_df %>%
      filter(form == variable_group_df[ind, "form"]) %>%
      select(variable_group_name, variable_group_description, variable)
    variable_group_df[ind, "variable_group"][[1]] <- list(temp_df)
  }
  
  # Form level
  form_df <- data.frame(variable_group_df %>%
                          select(form_group) %>%
                          unique())
  rownames(form_df) <- NULL
  

  for (ind in c(1:nrow(form_df))) {
    temp_df <- variable_group_df %>%
      #filter(form_group == variable_df[ind, "form_group"]) %>%
      select(form,form_description,form_name, variable_group)
    form_df[ind, "form"][[1]] <- list(temp_df)
  }
 
  # Study level
  complete_df <- data.frame('study_name' = fullname,
                       'study' = shortname,
                       'study_phs_number' = phs,
                       'study_url' = paste0("https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=",phs,".v",v,".p",p))

  complete_df$form_group <- list(form_df)
  
  
  
  # Save file
  my_json <- toJSON(complete_df, pretty=FALSE)
  json_string <- as.character(my_json)
  
  # Rename special fields
  #json_string <- gsub("field_note" , 'Field Note', json_string)
  
  fileConn <- file(paste0("../output/",shortname,"_metadata.json"))
  writeLines(json_string, fileConn)
  close(fileConn)
```
Decoding and additional file generation
```{r}

coding_df <- dd_raw[which(dd_raw$type=="encoded value"),]

coding_df$varname <- toupper(coding_df$varname)

for (filepath in data_files_list) {
  decoded_df <- read_csv(paste0("../input/",filepath),show_col_types = F)
  
  names(decoded_df) <- toupper(names(decoded_df))
  
  for (varid in names(decoded_df)[2:length(names(decoded_df))]) {
    #print(varid)

    if(varid%in%coding_df$varname){
          code_str=coding_df[which(coding_df$varname==varid),]$decoding
          
          #print(varid)
          
          codes_sep <- str_split(code_str,"\\|")
      
          for(code in codes_sep[[1]]){
            #print(code)
            coded_val = str_split(code,":")[[1]][1]
            #print(coded_val)
            true_val = str_split(code,":",)[[1]][2]
            #print(true_val)
            
            decoded_df[[varid]] <- replace(decoded_df[[varid]], which(decoded_df[[varid]]==coded_val), true_val)
          
        
      }
    }
  }
  
  tm_rp <- read_delim(file = paste0("../input/",phs,".v",v,".p",p,".txt") ,delim = "\t", show_col_types = F)
  
  tm_trim <- tm_rp[,c(7,1,3)]
  
  #names(tm_trim) <- tolower(names(tm_trim))
  
  names(tm_trim) <- c("c1","c2","c3")

  
  data_df <- decoded_df
  
  subj_id <- names(data_df)[1]
  
  #print(subj_id)
  
  data_df$DBGAP_SUBJECT_ID <- ""
  
  new_data_df <- data_df %>%
    select(DBGAP_SUBJECT_ID, everything())
  
  if(TRUE%in%(new_data_df[[subj_id]]%in%tm_trim$c2)){
    for (merge_i in c(1:length(new_data_df[[subj_id]]))) {
       if(new_data_df[[subj_id]][merge_i]%in%tm_trim$c2){
         new_data_df$DBGAP_SUBJECT_ID[merge_i] = tm_trim$c1[which(tm_trim$c2==new_data_df[[subj_id]][merge_i])]
       }else{
          print(paste0("Omitting subject ", new_data_df[[subj_id]][merge_i], " , no consent information provided"))
       }
    }
    
    new_data_df <- new_data_df[which(new_data_df$DBGAP_SUBJECT_ID!=""),]
    
    new_data_df[] <- lapply(new_data_df, as.character)
    new_data_df[is.na(new_data_df)] = ""
    write.csv(new_data_df,paste0("../output/",phs,".decoded_",filepath),row.names = F)
  
  header_df <- data.frame("c1"=c(paste0("# Study accession: ",phs,".v",v,".p",p),
                                        "# Table accession: subjects",
                                        "# Consent group: All",
                                        paste0("# Citation instructions: The study accession (",phs,".v",v,".p",p,") is used to cite the study and its data tables and documents. The data in this file should be cited using the accession subjects.v",v,".p",p),
                                         "# To cite columns of data within this file, please use the variable (phv#) accessions below:",
                                         "#",
                                         "# 1) the table name and the variable (phv#) accessions below; or",
                                         paste0("# 2) you may cite a variable as id.v",v,".p",p),
                                         "##",
                                          "dbGaP_Subject_ID"
                                          ), "c2"=c("","","","","","","","","subject_id",subj_id), "c3"=c("","","","","","","","","consent","CONSENT"))
  
  sm_df <- rbind(header_df,tm_trim)
  
  
  write.table(sm_df, file=paste0('../output/',phs,'.v',v,'.subjects.p',p,'.',shortname,'.Subject.MULTI.txt'), quote=FALSE, sep='\t', col.names = F, row.names = F)
  
  
  ### XML File
 
  doc = newXMLDoc()
  root = newXMLNode("data_table",attrs = c(id=paste0("subjects.v",v), study_id=paste0("phs002988.v",v), participant_set=paste0("p",p), date_created=date()), doc=doc)
  
  descNode = newXMLNode("description", "The subject consent data table includes subject IDs and consent group information.", parent = root)
  
  var1Node = newXMLNode("variable",attrs = c(id="subject_id"),parent=root)
  
  nm1Node = newXMLNode("name",subj_id,parent=var1Node)
  desc1Node = newXMLNode("description","Subject ID",parent=var1Node)
  ty1Node = newXMLNode("type","String",parent=var1Node)
  
  var2Node = newXMLNode("variable",attrs = c(id="consent"),parent=root)
  
  nm2Node = newXMLNode("name","CONSENT",parent=var2Node)
  desc2Node = newXMLNode("description","Consent group as determined by DAC",parent=var2Node)
  ty2Node = newXMLNode("type","encoded value",parent=var2Node)
  
  for (consent_i in c(1:length(consents_list))) {
    cval = newXMLNode("value",consents_list[consent_i],attrs = c(code=consent_i),parent = var2Node)
  }
  
  # OUTPUT XML CONTENT TO FILE
  saveXML(doc, file=paste0('../output/',phs,".v",v,".subjects.p",p,".",shortname,".Subject.data_dict.xml"),prefix = '<?xml-stylesheet type="text/xsl" href="./datadict_v1.xsl"?>')
    
  }else{
    print("Study subject ID does not match dbgap telemetry report")
    write.csv(decoded_df,paste0("../output/",phs,".decoded_",filepath),row.names = F)
  }  
}
```
