---
title: "CSSCD Metadata Curation"
author: "Emily Hughes"
date: "2/7/2022"
output: html_document
---

Library
```{r}
library(dplyr)
library(jsonlite)
```

Read in files
```{r}
phase1_metadata <- read.csv("../input/PHASE1_METADATA.csv")
phase2a_metadata <- read.csv("../input/PHASE2A_METADATA.csv")
phase23_metadata <- read.csv("../input/PHASE23_METADATA.csv")

file_info <- read.csv("../intermediates/csscd_fileinfo.csv")
```

Set up dataframe.
```{r}
phase1_metadata$raw_form_group_name <- "PHASE I"
phase2a_metadata$raw_form_group_name <- "PHASE II"
phase23_metadata$raw_form_group_name <- "PHASES 2 AND 3"


clean_up_df <- function(df){
  metadata <- df %>%
    select(raw_form_group_name, MEMNAME, NAME, TYPE, LABEL) %>%
    rename(data_file_name = MEMNAME, variable_id = NAME, variable_label_from_data_file = LABEL, variable_type = TYPE) %>%
    mutate(data_file_name = paste(tolower(data_file_name), '.sas7bdat', sep=''),
           variable_type = ifelse(variable_type==1, "continuous",
                                    ifelse(variable_type==2, "categorical", "unknown"))) %>%
    mutate(variable_type = ifelse(is.na(variable_type), "unknown", variable_type),
           variable_name = variable_label_from_data_file)
  #mini_file_info <- file_info %>% filter(form_group_name == metadata %>% pull(form_group_name) %>% unique())
  #raw <- full_join(metadata, file_info,
  #               by = c('form_group_name', 'data_file_name'))
  return(metadata)
}


p1__metadata <- clean_up_df(phase1_metadata)
p2a_metadata <- clean_up_df(phase2a_metadata)
p23_metadata <- clean_up_df(phase23_metadata)
```

Connect cleaned dfs to file_info.
```{r}
add_file_info <- function(df, file_info){
  rownames(df) <- NULL
  for(ind in 1:nrow(df)) {
    if (ind ==1) {
      file_name <- df[ind, 'data_file_name']
      study <- df[ind, 'raw_form_group_name']
      mini <- file_info %>% filter(str_detect(study, 'form_group_name'))
      return(mini)
    }
  }
}

test <- add_file_info(p1__metadata, file_info)
```


# levels of organization(broad to narrow)
- study
- form group
- form
- variable group
- variable

First create the variable level metadata
```{r}
combined <- rbind(p1__metadata, p23_metadata, p2a_metadata) %>% left_join(file_info, by = 'data_file_name')
variable_df <- combined %>% select(variable_id, variable_type, variable_name, data_file_name, form_group_name) %>% unique()
  
for(ind in 1:nrow(variable_df)){
  var_metadata_df <- combined %>% 
    filter(variable_id == variable_df[ind, 'variable_id'],
           data_file_name == variable_df[ind, 'data_file_name'],
           form_group_name == variable_df[ind, 'form_group_name']) %>%
    select(variable_label_from_data_file)
  variable_df[ind, 'variable_metadata'] [[1]] <- list(var_metadata_df) 
}
  
```

We don't have variable groups. Create the form level metadata
```{r}
form_df <- combined %>% select(form_name, form_description, data_file_name, form_group_name) %>% unique()

for(ind in 1:nrow(form_df)) {
  form_metadata_df <- variable_df %>%
    filter(data_file_name == form_df[ind, 'data_file_name'],
           form_group_name == form_df[ind, 'form_group_name']) %>%
    select(variable_id, variable_name, variable_type, variable_metadata)
  form_df[ind, 'variable'][[1]] <- list(form_metadata_df)
}


```

Create form group level metadata
```{r}
form_group_df <- combined %>% select(form_group_name, form_group_description) %>% unique()

for(ind in 1:nrow(form_group_df)) {
  form_group_metadata_df <- form_df %>%
    filter(form_group_name == form_group_df[ind, 'form_group_name']) %>%
    select(form_name, form_description, data_file_name, variable)
  form_group_df[ind, 'form'][[1]] <- list(form_group_metadata_df)
}



```

Create study level metadata

```{r}
study_df <- data.frame('study_name' = 'Cooperative Study of Sickle Cell Disease (CSSCD)',
                       'study' = 'CSSCD',
                       'study_phs_number' = 'phs002362',
                       'study_url' = 'https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=phs002362.v1.p1')
study_df$form_group <- list(form_group_df)

```

Write JSON file
```{r}
my_json <- toJSON(study_df, pretty=FALSE)

json_string <- as.character(my_json) # Convert to character/string
fileConn <- file("../output/csscd_metadata.json")
writeLines(json_string, fileConn)
close(fileConn)

# This works for writing a JSON file without the escape characters
```





