---
title: "MSH metadata curation"
author: "Emily Hughes"
date: "2/1/2022"
output: html_document
---

Libraries
```{r}
library(tidyverse)
library(jsonlite)
```

Read in input files
```{r}
pfu_metadata <- read.csv("../input/pfu_metadata.csv")
ext1_metadata <- read.csv("../input/ext1_metadata.csv")
clinical_metadata <- read.csv("../input/clinical_metadata.csv")
file_info <- read.csv("../intermediates/msh_file_info.csv")
```

Set up dataframe.
```{r}
pfu_metadata$form_group_name <- "Patient Follow-Up"
ext1_metadata$form_group_name <- "Extension I"
clinical_metadata$form_group_name <- "Clinical"

clean_up_df <- function(df, file_info){
  metadata <- df %>%
    select(form_group_name, MEMNAME, NAME, TYPE, LABEL) %>%
    rename(data_file_name = MEMNAME, variable_id = NAME, variable_label_from_data_file = LABEL, variable_type = TYPE) %>%
    mutate(data_file_name = paste(tolower(data_file_name), '.sas7bdat', sep=''),
           variable_type = ifelse(variable_type==1, "continuous",
                                    ifelse(variable_type==2, "categorical", "data missing"))) %>%
    mutate(variable_type = ifelse(is.na(variable_type), "data missing", variable_type),
           variable_name = variable_label_from_data_file)
  mini_file_info <- file_info %>% filter(form_group_name == metadata %>% pull(form_group_name) %>% unique())
  raw <- full_join(metadata, mini_file_info,
                 by = c('form_group_name', 'data_file_name'))
  return(raw)
}

pfu_metadata <- clean_up_df(pfu_metadata, file_info)
ext1_metadata <- clean_up_df(ext1_metadata, file_info)
clinical_metadata <- clean_up_df(clinical_metadata, file_info)
```

JSON formatting of the dataframe.
```{r}
# Variable metadata
variable_metadata <- function(raw) {
  var_meta <- raw %>% 
    select(form_group_name, form_name, form_description, data_file_name, variable_id, variable_name, variable_type) %>%
    unique()
  rownames(var_meta) <- NULL
  
  for(ind in 1:nrow(var_meta)) {
    vdf <- raw %>%
      filter(form_group_name == var_meta[ind, 'form_group_name'] &
               ((form_name == var_meta[ind, 'form_name']) | (is.na(form_name) == is.na(var_meta[ind, 'form_name']))) &
               data_file_name == var_meta[ind, "data_file_name"] &
               variable_id == var_meta[ind, 'variable_id']) %>%
      select(variable_label_from_data_file)
    #vdf <- data.frame(vdf)
    var_meta[ind, 'variable_metadata'][[1]] <- list(vdf)
  }
  return(var_meta)
}

pfu_var <- variable_metadata(pfu_metadata)
ext1_var <- variable_metadata(ext1_metadata)
clinical_var <- variable_metadata(clinical_metadata)

# variable group 
group_vars <- function(var_meta){
  var_group_name <- "All variables"
  var_group_description <- "All variables within the form"
  var_group <- var_meta %>% 
    select(form_group_name, form_name, form_description, data_file_name) %>%
    unique() %>%
    mutate(variable_group_name = var_group_name,
           variable_group_description = var_group_description)
  rownames(var_group) <- NULL
  for(ind in 1:nrow(var_group)){
    vgdf <- var_meta %>%
      filter(form_group_name == var_group[ind, 'form_group_name'] &
               ((form_name == var_group[ind, 'form_name']) | (is.na(form_name) == is.na(var_group[ind, 'form_name']))) &
               data_file_name == var_group[ind, 'data_file_name']) %>%
      select(variable_id, variable_name, variable_type, variable_metadata)
    var_group[ind, 'variable'][[1]] <- list(vgdf)
  }
  return(var_group)
}

pfu_group <- group_vars(pfu_var)
ext_group <- group_vars(ext1_var)
cli_group <- group_vars(clinical_var)


# form level/condense variable groups
form <- function(var_group){
  form_df <- var_group %>% 
    select(form_group_name, form_name, form_description, data_file_name) %>%
    unique()
  rownames(form_df) <- NULL

  for(ind in 1:nrow(form_df)){
    fdf <- var_group %>%
      filter(form_group_name == form_df[ind, 'form_group_name'] &
               ((form_name == form_df[ind, 'form_name']) | (is.na(form_name) == is.na(form_df[ind, 'form_name']))) &
               data_file_name == form_df[ind, 'data_file_name']) %>%
      select(variable_group_name, variable_group_description, variable)
    form_df[ind, 'variable_group'][[1]] <- list(fdf)
    }
  return(form_df)
}

pfu_form <- form(pfu_group)
ext_form <- form(ext_group)
cli_form <- form(cli_group)

# Form groups
form_groups <- function(form_df){
  form_groups <- form_df %>%
    select(form_group_name) %>%
    mutate(form_group_description = paste("All forms in", form_group_name)) %>%
    unique()
  rownames(form_groups) <- NULL
  
  for(ind in 1:nrow(form_groups)){
    fgdf <- form_df %>%
      filter(form_group_name == form_groups[ind, 'form_group_name']) %>%
      select(form_name, form_description, data_file_name, variable_group)
    form_groups[ind, 'form'][[1]] <- list(fgdf)
  }
  return(form_groups)
}
pfu_form_groups <- form_groups(pfu_form)
ext_form_groups <- form_groups(ext_form)
cli_form_groups <- form_groups(cli_form)
compiled <- rbind(pfu_form_groups, ext_form_groups, cli_form_groups)

# Study level
study_level <- function(form_groups) {
  study <- "MSH"
  study_url <- "https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=phs002348.v1.p1"
  study_name <- "Multicenter Study of Hydroxyurea (MSH)"
  study_phs_number <- "phs002348"
  
  final <- data.frame(study, study_name, study_phs_number, study_url)
  final[1, 'form_group'][[1]] <- list(form_groups)
  return(final)
}

final <- study_level(compiled)
```

Writing out to JSON.

```{r}
my_json <- as.character(toJSON(final, pretty=FALSE))
```


Using the `write_json` function outputs quotations with escape characters ("/"). This causes problems with the JSON file format. This can be dealt with by converting the JSON object into a string and writing this to a text file.

```{r}
fileConn <- file("../output/msh_metadata.json")
writeLines(my_json, fileConn)
close(fileConn)
```
