---
title: "ACTIV4a Metadata Curation"
author: "Michael Corace"
date: "N/A"
output: html_document
---

Libraries
```{r}
library(jsonlite)
library(tidyverse)
install.packages("readxl")
library(readxl)
library(dplyr)
library(stringr)
library(jsonlite)
```

To-Do
******

Bring relevant csv files into R data frames
```{r}

domain_names_df <- read.csv("~/Documents/pic-sure-metadata-curation/activ4a/input/updated/domain_names.csv")

path <- "~/Documents/pic-sure-metadata-curation/activ4a/input/updated/Data Dictionary 2023-03-08.xlsx"

#getting info about all excel sheets
sheets <- readxl::excel_sheets(path)
tibble <- lapply(sheets, function(x) readxl::read_excel(path, sheet = x))
dd_df <- lapply(tibble, as.data.frame)
    
# assigning names to data frames
names(dd_df) <- sheets


for(form_name in names(dd_df)){
  tmp_df <- dd_df[[form_name]]
  
  n <- length(tmp_df[[1]])
  
  dd_df[[form_name]] <- cbind(tmp_df,
                              data.frame("form_id"=rep(domain_names_df$Domain[which(domain_names_df$Domain==form_name)], each=n),
                                         "form_name"=rep(domain_names_df$Full[which(domain_names_df$Domain==form_name)], each=n),
                                         "form_group"=rep(domain_names_df$Group[which(domain_names_df$Domain==form_name)], each=n)))
}

#dd_df_full<- dd_df %>% reduce(full_join, by = "VARNAME") 

dd_df_full <- do.call("rbind",dd_df)
```


Filter variable csv to useful information, and renaming columns to match
```{r}
renamed_df <-  data.frame(
                            form_group=dd_df_full$form_group,
                            form=dd_df_full$form_id,
                            form_name= dd_df_full$form_name,
                            form_description= "Form description not provided",
                            variable_id=toupper(dd_df_full$VARNAME),
                            variable_name=dd_df_full$VARDESC,
                            variable_type=dd_df_full$TYPE,
                            variable_group_name="All variables",
                            variable_group_description="All variables within the group",
                            variable_description=dd_df_full$VARDESC,
                            order=dd_df_full$ORDER,
                            attacc=dd_df_full$ATTACC,
                            protect=dd_df_full$PROTECT
                            )

renamed_df$variable_name[is.na(renamed_df$variable_name)] <- "Name not provided"

```


Build Hierarchy tree
```{r}
trees_vector <- vector(mode = "character",length = length(renamed_df$variable_id))

for (i in c(1:length(renamed_df$variable_id))) {
  study <- "ACTIV-4a"
  form_group <- str_replace_all(renamed_df$form_group[i],"/","-")
  form <- str_replace_all(renamed_df$form[i],"/","-")
  
  form_name <- str_replace_all(renamed_df$form_name[i],"/","-")
  #variable_group <- 
  variable <- str_replace_all(renamed_df$variable_name[i],"/","-")
  if(variable=="Name not provided"){
    variable <- str_replace_all(renamed_df$variable_id[i],"/","-")
  }
  
  if(form_name =="Full Form Name Not Provided"){
    if(form_group=="Ungrouped Forms"){
          tree <- paste0(study, "/",form, "/",variable)
    }else{
          tree <- paste0(study, "/",form_group,"/",form, "/",variable)
    }
  }else{
    if(form_group=="Ungrouped Forms"){
          tree <- paste0(study, "/",form," : ", form_name, "/",variable)
    }else{
          tree <- paste0(study, "/",form_group,"/",form," : ", form_name, "/",variable)
    }
  }
  
  trees_vector[i] <- tree
}  


full_df <- cbind(renamed_df, trees_vector)
names(full_df)[names(full_df) == 'trees_vector'] <- 'data_hierarchy'

```



Variable information
```{r}
renamed_df<-full_df

variable_info_df <- data.frame(renamed_df %>%
                         select(form_group,form,form_description,form_name,variable_group_name, variable_group_description, variable_id,variable_name,variable_type, order,attacc,protect, data_hierarchy,variable_description ) %>%
                         unique())
rownames(variable_info_df) <- NULL



for (ind in c(1:nrow(variable_info_df))) {
  temp_df <- data.frame(renamed_df[ind,] %>% #$variable_description
                          select(#variable_description,
                            #data_hierarchy,
                            order,
                            protect,
                            attacc
                           )
                        )
  
  temp_df<-temp_df %>% mutate_all(na_if,"")
  
  variable_info_df[ind, "derived_variable_level_data"][[1]] <- list(temp_df)
}
```


Variable
```{r}
variable_df <- data.frame(variable_info_df %>%
                         select(form_group,form,form_description,form_name,variable_group_name, variable_group_description) %>%
                         unique())
rownames(variable_df) <- NULL


for (ind in c(1:nrow(variable_df))) {
  temp_df <- variable_info_df %>%
    filter(form == variable_df[ind, "form"], variable_group_name == variable_df[ind, "variable_group_name"]) %>%
    select(variable_id, 
          variable_name, 
          variable_type,
          variable_description,
          data_hierarchy, 
          derived_variable_level_data)
  variable_df[ind, "variable"][[1]] <- list(temp_df)
}
```


Variable Group
```{r}
variable_group_df <- data.frame(variable_df %>%
                         select(form_group,form,form_name,form_description) %>%
                         unique())
rownames(variable_group_df) <- NULL


for (ind in c(1:nrow(variable_group_df))) {
  temp_df <- variable_df %>%
    filter(form == variable_group_df[ind, "form"]) %>%
    select(variable_group_name, variable_group_description, variable)
  variable_group_df[ind, "variable_group"][[1]] <- list(temp_df)
}
```


Form
```{r}

#variable_group_df[variable_group_df==""] <- "Form name not provided"

#form_descriptions_df <- data.frame(form=raw_forms_df$id, form_description=raw_forms_df$display_name)

#variable_group_df <- merge(variable_group_df,form_descriptions_df, by="form", all = TRUE)

form_df <- data.frame(variable_group_df %>%
                         select(form_group) %>%
                         unique())
rownames(form_df) <- NULL


for (ind in c(1:nrow(form_df))) {
  temp_df <- variable_group_df %>%
    #filter(form_group == variable_df[ind, "form_group"]) %>%
    select(form,form_description,form_name, variable_group)
  form_df[ind, "form"][[1]] <- list(temp_df)
}
```

Study
```{r}
complete_df <- data.frame('study_name' = 'COVID-19 ACTIV-4 ACUTE: A Multicenter, Adaptive, Randomized Controlled Platform Trial of the Safety and Efficacy of Antithrombotic Strategies in Hospitalized Adults with COVID-19 (ACTIV4A)',
                       'study' = 'ACTIV4a',
                       'study_phs_number' = 'phs002694',
                       'study_url' = 'https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=phs002694.v3.p1')

complete_df$form_group <- list(form_df)
```

To json
```{r}
my_json <- toJSON(complete_df, pretty=FALSE)
json_string <- as.character(my_json) # Convert to character/string

# Rename special fields
json_string <- gsub("order" , 'ORDER', json_string)
json_string <- gsub("attacc" , 'ATTACC', json_string)
json_string <- gsub("protect" , 'PROTECT', json_string)


#names(wide_df)[names(wide_df) == 'variable_was_computed'] <- '\"Computed Variable?\"'
#names(wide_df)[names(wide_df) == 'variable_hct_status'] <- '\"HCT status\"'
#names(wide_df)[names(wide_df) == 'variable_question_number_inform'] <- '\"CIBMTR Form number; (question numbers)\"'
```


Write File
```{r}
fileConn <- file("../output/activ4a_metadata.json")
writeLines(json_string, fileConn)
close(fileConn)
```

