---
title: "Curate Metadata for NSRR CFS"
author: "Michael Corace"
date: "7/6/2022"
output: html_document
---

Libraries
```{r}
library(jsonlite)
library(tidyverse)
install.packages("readxl")
library(readxl)
library(dplyr)
library(stringr)
library(jsonlite)
```

To-Do
******

Bring relevant csv files into R data frames
```{r}

raw_forms_df <- read.csv("../input/cfs-data-dictionary-0.7.0-forms.csv")

raw_variables_df <- read.csv("../input/cfs-data-dictionary-0.7.0-variables.csv")

dataset_df <- read.csv("../input/cfs-visit5-dataset-0.7.0-censored-for-bdc.csv")

harmonized_df <- read.csv("../input/cfs-visit5-harmonized-dataset-0.7.0-censored-for-bdc.csv")

```


Filter variable csv to useful information, and renaming columns
```{r}

renamed_df <-  data.frame(
                            form_group="All forms within the study",
                            form=raw_variables_df$forms,
                            #form_description=,
                            variable_id=toupper(raw_variables_df$id),
                            variable_name=raw_variables_df$display_name,
                            variable_type=raw_variables_df$type,
                            variable_group_name=raw_variables_df$folder,
                            variable_group_description="All variables within the group",
                            variable_description=raw_variables_df$description,
                            variable_labels=raw_variables_df$labels,
                            units=raw_variables_df$units,
                            calculation=raw_variables_df$calculation,
                            commonly_used=raw_variables_df$commonly_used
                            )

```

Variable information
```{r}
variable_info_df <- data.frame(renamed_df %>%
                         select(form_group,form,variable_group_name, variable_group_description, variable_id,variable_name,variable_type) %>%
                         unique())
rownames(variable_info_df) <- NULL



for (ind in c(1:nrow(variable_info_df))) {
  temp_df <- data.frame(renamed_df[ind,] %>% #$variable_description
                          select(variable_description,
                            variable_labels,
                            units,
                            calculation,
                            commonly_used
                           )
                        )
  if(temp_df[1,]$commonly_used==""){
    temp_df[1,]$commonly_used <- "False"
  }
  
  temp_df<-temp_df %>% mutate_all(na_if,"")
  
  variable_info_df[ind, "variable_information"][[1]] <- list(temp_df)
}
```


Variable
```{r}
variable_df <- data.frame(variable_info_df %>%
                         select(form_group,form,variable_group_name, variable_group_description) %>%
                         unique())
rownames(variable_df) <- NULL


for (ind in c(1:nrow(variable_df))) {
  temp_df <- variable_info_df %>%
    filter(form == variable_df[ind, "form"], variable_group_name == variable_df[ind, "variable_group_name"]) %>%
    select(variable_id, variable_name, variable_type, variable_information)
  variable_df[ind, "variable"][[1]] <- list(temp_df)
}
```


Variable Group
```{r}
variable_group_df <- data.frame(variable_df %>%
                         select(form_group,form) %>%
                         unique())
rownames(variable_group_df) <- NULL


for (ind in c(1:nrow(variable_group_df))) {
  temp_df <- variable_df %>%
    filter(form == variable_group_df[ind, "form"]) %>%
    select(variable_group_name, variable_group_description, variable)
  variable_group_df[ind, "variable_group"][[1]] <- list(temp_df)
}
```


Form
```{r}

variable_group_df[variable_group_df==""] <- "Form name not provided"

form_descriptions_df <- data.frame(form=raw_forms_df$id, form_description=raw_forms_df$display_name)

variable_group_df <- merge(variable_group_df,form_descriptions_df, by="form", all = TRUE)

form_df <- data.frame(variable_group_df %>%
                         select(form_group) %>%
                         unique())
rownames(form_df) <- NULL


for (ind in c(1:nrow(form_df))) {
  temp_df <- variable_group_df %>%
    #filter(form_group == variable_df[ind, "form_group"]) %>%
    select(form, form_description, variable_group)
  form_df[ind, "form"][[1]] <- list(temp_df)
}
```

Study
```{r}
complete_df <- data.frame('study_name' = 'National Sleep Research Resource (NSRR): Cleveland Family Study (CFS)',
                       'study' = 'nsrr_cfs',
                       'study_phs_number' = 'phs002715',
                       'study_url' = 'https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=phs002715.v1.p1')

complete_df$form_group <- list(form_df)
```

To json
```{r}
my_json <- toJSON(complete_df, pretty=FALSE)
json_string <- as.character(my_json) # Convert to character/string
fileConn <- file("../output/nsrr_cfs_metadata.json")
writeLines(json_string, fileConn)
close(fileConn)
```

