Libraries
```{r}
library(jsonlite)
library(tidyverse)
#install.packages("readxl")
library(readxl)
library(dplyr)
library(stringr)
library(jsonlite)
#install.packages("sas7bdat")
library(sas7bdat)
library(haven)
library(XML)
```

Fill out inputs for the study
```{r}
phs='RAS_TEST'
#v=1
#p=1
shortname='RAS_TEST'
fullname='RAS Test Studies BDC Dummy Data'
dd_filepath="../input/ras_test_data_dictionary.csv"
#data_files_list=c()
#variable_level_data_list=c()
#consents_list=c('')
#focus=''
#design=''
#assosciated_studies=' '
#additional_info=' '
#harmonized=''
#study_type=''
#gen3_project_name=''
#new_up="New Study"
#s3_folder="//"
#synthetic=""
```

```{r}

dd_raw <- read_csv(dd_filepath, show_col_types = F)


renamed_df <-  data.frame(
                            form_group="N/A",
                            form=dd_raw$`Data File ID`,
                            form_name= dd_raw$`Data File Name`,
                            form_description= "N/A",
                            variable_id=toupper(dd_raw$`Variable ID`),
                            variable_type='N/A',
                            variable_group_name='NA',
                            variable_group_description="N/A",
                            variable_description=dd_raw$`Variable Description`,
                            variable_name=dd_raw$`Variable Name`,
                            concept_path=dd_raw$`Concept path`
                            )
```


Json
```{r}
# Heirarchy tree
  trees_vector <- vector(mode = "character",length = length(renamed_df$variable_id))

  for (i in c(1:length(renamed_df$variable_id))) {
    study <- shortname
    
    form <- str_replace_all(renamed_df$form_name[i],"/","-")
     
    variable <- str_replace_all(renamed_df$variable_name[i],"/","-")
    
    tree <- paste0(study, "/",form, "/",variable)

    trees_vector[i] <- tree
  }  

  full_df <- cbind(renamed_df, trees_vector)
  names(full_df)[names(full_df) == 'trees_vector'] <- 'data_hierarchy'

# Var information level
  variable_info_df <- data.frame(
    full_df %>%
      select(
        form_group,
        form,
        form_description,
        form_name,
        variable_group_name,
        variable_group_description,
        variable_id,
        variable_name,
        variable_type,
        data_hierarchy,
        variable_description,
        concept_path
      ) %>%
      unique()
  )
  rownames(variable_info_df) <- NULL



  for (ind in c(1:nrow(variable_info_df))) {
    temp_df <- data.frame(full_df[ind,] %>% #$variable_description
                  select(
                    concept_path
                   )
                )
    
    temp_df<-temp_df %>% mutate_all(na_if,"")
    
    variable_info_df[ind, "derived_variable_level_data"][[1]] <- list(temp_df)
  }
  
  # Var level
  variable_df <- data.frame(
    variable_info_df %>%
      select(
        form_group,
        form,
        form_description,
        form_name,
        variable_group_name,
        variable_group_description
      ) %>%
      unique()
  )
  rownames(variable_df) <- NULL


  for (ind in c(1:nrow(variable_df))) {
    temp_df <- variable_info_df %>%
      filter(form == variable_df[ind, "form"], variable_group_name == variable_df[ind, "variable_group_name"]) %>%
      select(variable_id, 
            variable_name, 
            variable_type,
            variable_description,
            data_hierarchy, 
            derived_variable_level_data)
    variable_df[ind, "variable"][[1]] <- list(temp_df)
  }
  
  # Var group level
  variable_group_df <- data.frame(variable_df %>%
                                    select(form_group, form, form_name, form_description) %>%
                                    unique())
  rownames(variable_group_df) <- NULL
  

  for (ind in c(1:nrow(variable_group_df))) {
    temp_df <- variable_df %>%
      filter(form == variable_group_df[ind, "form"]) %>%
      select(variable_group_name, variable_group_description, variable)
    variable_group_df[ind, "variable_group"][[1]] <- list(temp_df)
  }
  
  # Form level
  form_df <- data.frame(variable_group_df %>%
                          select(form_group) %>%
                          unique())
  rownames(form_df) <- NULL
  

  for (ind in c(1:nrow(form_df))) {
    temp_df <- variable_group_df %>%
      #filter(form_group == variable_df[ind, "form_group"]) %>%
      select(form,form_description,form_name, variable_group)
    form_df[ind, "form"][[1]] <- list(temp_df)
  }
 
  # Study level
  complete_df <- data.frame('study_name' = fullname,
                       'study' = shortname,
                       'study_phs_number' = phs,
                       'study_url' = paste0("https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=",phs,".v",v,".p",p))

  complete_df$form_group <- list(form_df)
  
  
  
  # Save file
  my_json <- toJSON(complete_df, pretty=FALSE)
  json_string <- as.character(my_json)
  
  # Rename special fields
  #json_string <- gsub("field_note" , 'Field Note', json_string)
  
  fileConn <- file(paste0("../output/",shortname,"_metadata.json"))
  writeLines(json_string, fileConn)
  close(fileConn)
```
