---
title: "decoding numom2b"
author: "michael corace"
date: "2023-05-04"
output: html_document
---

Libraries
```{r}
library(jsonlite)
library(tidyverse)
#install.packages("readxl")
library(readxl)
library(dplyr)
library(stringr)
library(jsonlite)
```



```{r}

dd_list <- list.files("~/Documents/pic-sure-metadata-curation/numom2b/inputs/data_dictionaries")

ds_list <- list.files("~/Documents/pic-sure-metadata-curation/numom2b/inputs/datasets")

```

```{r}

for(file_i in c(1:length(ds_list))){

dd_df <- read_xlsx(paste0("~/Documents/pic-sure-metadata-curation/numom2b/inputs/data_dictionaries/", dd_list[file_i])) 
ds_df <- read.csv(paste0("~/Documents/pic-sure-metadata-curation/numom2b/inputs/datasets/", ds_list[file_i]), sep = "\t")


decoded_df <- ds_df


for(i in c(1:length(dd_df$VARNAME))){
  varname <- dd_df$VARNAME[i]
  
  for (q in c(6:length(dd_df[i,]))) {
    val=dd_df[[i,q]]
    if(!is.na(val)) {
       if(val!="=Missing"){
        #print(val)
      
        raw_val <- str_split(val,"=")[[1]][1]
        decoded_val <- str_split(val,"=")[[1]][2]
      
        decoded_df[[varname]] <- replace(decoded_df[[varname]],decoded_df[[varname]]==raw_val,decoded_val)
      
        #varname_list <- append(varname_list,dd_df$VARNAME[i])
        #raw_val_list <- append(raw_val_list,raw_val)
        #decoded_val_list <- append(decoded_val_list,decoded_val)
      
      }else{
        decoded_df[[varname]] <- replace(decoded_df[[varname]],is.na(decoded_df[[varname]]),"Missing")
      }
    }
  }
}
decoded_df <- replace(decoded_df,is.na(decoded_df),"")
names(decoded_df)<- toupper(names(decoded_df))

write_csv(decoded_df,paste0("~/Documents/pic-sure-metadata-curation/numom2b/outputs/decoded_data/",str_remove(ds_list[file_i],".txt"), ".csv"))
}
```
